### ISSUE TITLE
Facebook videos will not load when using uBlock + uMatrix

### ISSUE THREAD

**Issue by alxpettit** [uBlockOrigin/uMatrix-issues#26] opened 2018-06-22 15:15 UTC
I'm told I need to provide supporting logs, but I don't see ANYTHING noteworthy happening in the log. It seems this error is happening at a very low level.

* This bug happens only when uMatrix and uBlock are both installed, bizarrely enough. Thus, I wasn't sure which repo to open it in. Let me know if it should be moved.
* The bug occurs _even_ when uMatrix and uBlock are both disabled for the Facebook domain, and are copied straight out of the box with no user configurations.

Software versions:
* Arch Linux running 4.14.50-1-lts kernel
* Chromium 67.0.3396.87
* uMatrix 1.3.10
* uBlock Origin 1.16.10

Steps to recreate:
1. Open a new profile.
2. Install uBlock & uMatrix
3. Open Facebook.
4. Disable both extensions for Facebook domain.
5. Attempt to watch Facebook videos. You will observe many of them failing to load. For a specific example, try to watch this one: https://www.facebook.com/JungleVT/videos/1872398756235291/

It's notable that if a video is cached, it will play correctly. However, videos that were not watched before setting up the extensions will fail to cache.

**Comment by uBlock-user** [comment] 2018-06-22 15:17
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/19

**Closed by uBlock-user** 2018-06-22 15:17 UTC

**Comment by gorhill** [comment] 2018-06-22 16:12
A ruleset recipe was added for Facebook lately, did you try to use it?

**Comment by alxpettit** [comment] 2018-06-22 16:13
@gorhill I wasn't aware. Link?

**Comment by alxpettit** [comment] 2018-06-22 16:21
@gorhill Disabling "spoof referrer header" on the Facebook domain worked, per uBlock-user's instructions on the linked issue.

I'm confused as to _exactly why_ this works, though. I read [this](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches), and I'm still confused as to precisely which code in Facebook is broken and why when it's enabled.

**Comment by uBlock-user** [comment] 2018-06-22 16:42
@alxpettit Facebook's CDN server has a referrer policy setup, hence this issue. This happened two weeks ago, so it worked before but not anymore.

**Comment by uBlock-user** [comment] 2018-06-22 19:49
> then uMatrix messed up its verification thingy

uMatrix didn't mess up, uMatrix Spoofs HTTP referrer string of third-party requests, facebook's CDN server `fbcdn.net` is third-party because we're visiting `facebook.com`, not `fbcdn.net` but the video loads from `fbcdn.net`, so whatever referrer policy `fbcdn.net` has set for `facebook.com` it expectation is not being fulfilled by uMatrix's spoofing hence you get trolled repeatedly and the console gets spammed CORS errors.

**Comment by alxpettit** [comment] 2018-06-22 19:51
> uMatrix didn't mess up

I meant, uMatrix messed up _facebook's_ CDN verification thingy. Not that this is a uMatrix bug! If I thought it was a bug, I'd be trying to get the issue reopened! :P

**Comment by uBlock-user** [comment] 2018-06-22 20:03
This only happens on `facebook.com` though, if you try to play a facebook video embedded on a blog, then it will run just fine.

**Comment by alxpettit** [comment] 2018-06-22 20:05
@uBlock-user

Wait, really? Why would that be? If we're playing a video embedded in a blog, our domain name wouldn't match `fbcdn.net` there either. Seems like the same software logic should apply, unless Facebook is doing some special with embedded videos.

**Comment by uBlock-user** [comment] 2018-06-22 20:13
They add the change on embedded videos too now. It used to work two weeks ago. I just tested [here](https://www.shoutmeloud.com/how-to-embed-a-facebook-video-on-your-website-or-blog-post.html) and it will display `Video not available` error, a misleading change because as soon as you disable referrer spoofing and refresh it loads normally.

**Comment by uBlock-user** [comment] 2018-06-22 20:46
@alxpettit If you're really feel stubborn about keeping referrer spoofing enabled, then you can use this hack : - 

Install ModHeader or any HTTP headers manipulating extension and set [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) to `*` in Response Headers. That will no longer throw CORS errors and it will start working back as it was before.

**Comment by uBlock-user** [comment] 2018-06-23 18:01
> why does this only happen when both extensions are installed?

It will happen as long as you're spoofing referrer with any extension and not just uMatrix,  and not related to uBlock Origin to have it occurr, this will happen with uMatrix alone too. 

> Does anyone want to explain the rationale?

By-design. https://github.com/gorhill/uMatrix/wiki/Per-scope-switches

**Comment by Remu-rin** [comment] 2018-06-23 20:49
Also https://github.com/gorhill/uMatrix/wiki/About-%22the-page-is-still-broken-after-I-created-all-necessary-rules%22
> Did you verify that one or more per-scope switches are also interfering?
> Keep in mind that the per-scope switches are independent of the matrix filtering switch, so stuff can still be blocked/modified when per-scope switches are enabled.
