### ISSUE TITLE
Excessively long FQDN minor UI formatting

### ISSUE THREAD

**Issue by shoffmeister** [uBlockOrigin/uMatrix-issues#45] opened 2018-08-27 09:41 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Long FQDN pose a problem for umatrix when it comes to showing them - they are simply not "recognizable"
It would seem as if some means to show the full FQDN needs to be figured out?

### A specific URL where the issue occurs

I get the problem to show on a Microsoft Office 365 account, with OneNote - unfortunately, I cannot link to that; for me this looks like https://private-thing-my.sharepoint.com/:o:/r/personal/my_personal_thing/_layouts/15/WopiFrame.aspx?sourcedoc=%7B5EAC589D-AAAA-41D6-ADD9-C81EC450366D%7D&file=... but that will be unavailable to anyone but me.

### Steps to Reproduce

Browse to Microsoft Office 365 account, with OneNote - play around a little.

I suppose this is part of a larger challenge, where content-delivery networks now use DNS a lot to direct clients to specific locations.

### Supporting evidence

![umatrix_ui_overflow](https://user-images.githubusercontent.com/3868036/44652789-205b5580-a9ed-11e8-9978-cd7257e8822b.jpeg)

### Your environment

* uMatrix version: 1.3.12 (rolling with Firefox)
* Browser Name and version: Firefox 61.0.2 (whatever Fedora keeps rolling)
* Operating System and version: Linux Fedora 28 (fully up-to-date)

**Comment by gorhill** [comment] 2018-08-27 10:27
Duplicate of <https://github.com/gorhill/uMatrix/issues/182>.

**Closed by gorhill** 2018-08-27 10:27 UTC
Labels: duplicate

**Comment by uBlock-user** [comment] 2018-08-27 11:12
https://github.com/gorhill/httpswitchboard/issues/133#issuecomment-42762309
