### ISSUE TITLE
Matrix popup is cropped by slider if list is longer

### ISSUE THREAD

**Issue by Tilo-R** [uBlockOrigin/uMatrix-issues#256] opened 2020-05-06 06:44 UTC
### Prerequisites

- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X ] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

If the list of (sub-) domains is too long to fit into the popup matrix, a vertical slider is shown at the right side of the matrix. This slider overlaps with the right half of the rightmost colum ("others") which makes this column hard to read.
The "correct" behaviour could be:
a) a matrix window that is slightly wider and provides space for the slider, even if it's not used;
b) a matrix window that becomes wider as soon as the slider gets visible.

### A specific URL where the issue occurs

none - or many. :-)
wetter.de may serve as an example (see screenshots).

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

No particular steps required.

### Ruleset

The behaviour is independent of the ruleset.

### Supporting evidence

Screenshots attached.

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Fx 75.0
* Operating System and version: W10 (1909)

Screenshots:
![uMatrix-small](https://user-images.githubusercontent.com/64888443/81145022-ab883f00-8f75-11ea-81c4-cbfc6b5cd8bd.png)
![uMatrix-large](https://user-images.githubusercontent.com/64888443/81145032-b04cf300-8f75-11ea-848c-9af8873585d0.png)

**Comment by uBlock-user** [comment] 2020-05-06 06:55
Duplicate of https://github.com/gorhill/uMatrix/issues/811

**Closed by uBlock-user** 2020-05-06 06:55 UTC

**Comment by Tilo-R** [comment] 2020-05-06 07:02
Sorry - since that problem persists, I didn't search the "closed" issues deeper...
