### ISSUE TITLE
How to add uMatrix to the context menu

### ISSUE THREAD

**Issue by noci2012** [uBlockOrigin/uMatrix-issues#35] opened 2018-07-23 20:17 UTC
When the menu bar hidden / and only the search bar is show in readonly mode...
(  https://www.bnr.nl/player/live ) uMatrix is not visible..., causing problems foradjusten site allowance.

On the BNR.NL site just play the live audio. uMatrix is not manageble.
Image:
[https://i.imgur.com/GcdZ6ew.png](url)
### Your environment
uMatrix: 1.3.12
Chromium Version 67.0.3396.87 (Developer Build) (64-bit)
Linux 4.14.52
* uMatrix version:
* Browser Name and version:
* Operating System and version:

**Comment by gwarser** [comment] 2018-07-23 21:30
Duplicate of https://github.com/gorhill/uMatrix/issues/947

**Closed by gwarser** 2018-07-23 21:30 UTC

**Comment by noci2012** [comment] 2018-08-22 17:09
ok thanks.
