### ISSUE TITLE
subdomain wildcard

### ISSUE THREAD

**Issue by FernandoMiguel** [uBlockOrigin/uMatrix-issues#47] opened 2018-09-03 13:27 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

add support for subdomain wildcard rules

example:
```
github.com *.githubusercontent.com image allow
```

**Comment by uBlock-user** [comment] 2018-09-03 14:00
Duplicate of https://github.com/gorhill/uMatrix/issues/519

**Closed by uBlock-user** 2018-09-03 14:00 UTC
