### ISSUE TITLE
Cookies missing on very first request if website has service worker with fetch event handler (1.3.17rc3)

### ISSUE THREAD

**Issue by steffenweber** [uBlockOrigin/uMatrix-issues#162] opened 2019-05-28 10:28 UTC
Could you please re-open the following issue? The problem has reappeared in uMatrix 1.3.17rc3: https://github.com/uBlockOrigin/uMatrix-issues/issues/155

(I replied there but [it seems like you don't read new comments on closed bug reports](https://github.com/uBlockOrigin/uMatrix-issues/issues/156#issuecomment-494763587). No offense. :slightly_smiling_face:)

**Comment by uBlock-user** [comment] 2019-05-28 11:11
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/155

**Closed** 2019-05-28 11:10 UTC
