### ISSUE TITLE
background images bypass umatrix rules

### ISSUE THREAD

**Issue by jrynd** [uBlockOrigin/uMatrix-issues#88] opened 2018-12-14 20:23 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Taboola, an ad network, is blocked. Yet Taboola ads show up on the site. I don't think Taboola scripts are running, but Taboola images are definitely shown (and Taboola is able to start profiling me)

### A specific URL where the issue occurs

https://slate.com/human-interest/2018/11/stop-drinking-friends-advice.html
### Steps to Reproduce

1. Block Taboola.com
2. Go to https://slate.com/human-interest/2018/11/stop-drinking-friends-advice.html
3. See the Taboola images at bottom of page

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Chrome Version 71.0.3578.80 (Official Build) (64-bit)
* Operating System and version: Windows 10 Enterprise 10.0.15063 Build 15063
![umatrix](https://user-images.githubusercontent.com/2706662/50025455-98a55100-ffb3-11e8-84e7-6dee746870fb.PNG)
![taboola](https://user-images.githubusercontent.com/2706662/50025461-9e029b80-ffb3-11e8-8425-fe055381b61f.PNG)
![inspect](https://user-images.githubusercontent.com/2706662/50025463-a064f580-ffb3-11e8-9d1a-3fc4473dd49f.PNG)
![log](https://user-images.githubusercontent.com/2706662/50025499-c7232c00-ffb3-11e8-8b26-0ed749e09845.PNG)

**Comment by jrynd** [comment] 2018-12-14 20:24
Note that some Taboola requests are blocked but others are allowed.

**Comment by uBlock-user** [comment] 2018-12-14 20:30
> See the Taboola images at bottom of page

Not seeing any.

**Comment by uBlock-user** [comment] 2018-12-14 20:40
The last page shows 3rd party tabless requests are not being blocked, that's where that content is being loaded.

Open `chrome://serviceworker-internals/` and remove any and all service workers listed and try again.

**Comment by gorhill** [comment] 2018-12-14 21:09
I am unable to reproduce, the service worker fails to launch on my side, console:

    ServiceWorker registration failed:  TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed

**Comment by gorhill** [comment] 2018-12-14 21:13
Ok so if I soft-allow all for that site, the worker launched. But I don't see it pulling anything from `taboola.com`, only from `storage.googleapis.com` and itself.

**Comment by jrynd** [comment] 2018-12-14 21:13
I do indeed have a service worker for slate.com. I tried both stopping the slate.com and removing the slate.com worker, but when I go back to the page and reload, the worker gets re-enabled and the images show.

**Comment by jrynd** [comment] 2018-12-14 21:15
How do I get it to block 3rd party tabless requests?

**Comment by gorhill** [comment] 2018-12-14 21:15
Without more details about your rules and how you configured uMatrix, not much we can do -- we can't reproduce.

**Comment by jrynd** [comment] 2018-12-14 21:15
What more details do you need? Should I paste the rules here?

**Comment by gorhill** [comment] 2018-12-14 21:16
You will need to install the dev build to get the appropiate UI from the logger to set rules for tabless requests.

**Comment by uBlock-user** [comment] 2018-12-15 08:37
Take a backup and reset uMatrix to its default settings and try to reproduce again.

**Comment by gorhill** [comment] 2018-12-16 10:18
We need to leave him time to report back before closing. I want to understand what is happening here.

**Comment by gorhill** [comment] 2018-12-18 13:36
> journal processing bug that uMatrix also suffers from ?

You seem to imply there is a "journal processing bug" in uBO. I don't see any issue opened about "journal processing" in uBO's issue trackers.

**Comment by uBlock-user** [comment] 2018-12-18 13:51
> I don't see any issue opened about "journal processing" in uBO's issue trackers.

https://github.com/uBlockOrigin/uBlock-issues/issues/155#issuecomment-410455636

and the bug in question that uBO suffered from - https://github.com/gorhill/uBlock/issues/2053

**Comment by uBlock-user** [comment] 2018-12-18 14:07
actually `storage.googleapis.com` doesn't appear in uBO's dynamic filtering pane either, but appears in the logger -

![](https://i.gyazo.com/ae55393f38950a2f60af22409af0567b.png)
![](https://i.gyazo.com/0d81df7762e3a111fbb7c6bd42270818.png)

`requestJournalingPeriod` in uBO is set to 1000 which is the default value and I never changed it, so this shouldn't happen.

**Comment by gorhill** [comment] 2018-12-18 14:10
Yes, because it is tabless.

**Comment by uBlock-user** [comment] 2018-12-18 14:11
So tabless requests won't be appearing in the filtering pane ? Didn't know that.

**Comment by gorhill** [comment] 2018-12-18 14:13
It has **always** been like tab, the pane reports what is seen in a specific tab, a network request being tabless makes it impossible to know from which specific tab it originate.

**Comment by uBlock-user** [comment] 2018-12-18 14:16
I just checked the **Context** in uBO logger it's `slate.com`, and yet it is tabless why ?

**Comment by gorhill** [comment] 2018-12-18 14:19
> it is tabless why ?

Because the extensions API said so, the tab is `-1`. Can we stop adding unrelated stuff to this issue please?

**Comment by uBlock-user** [comment] 2018-12-18 14:22
> Can we stop adding unrelated stuff to this issue please?

Sure, I will delete our comments to remove the clutter.

**Comment by jrynd** [comment] 2018-12-19 15:42
Here are the steps I took:
1.  Disabled umatrix 1.3.14
2.  Downloaded umatrix development build from link given, got 1.3.15.101 (the mouseover says "umatrix dev build")
3.  Backed up settings and rules list
4.  Reset to default settings
5.  Visited the slate site. Taboola does not load, there's not even a request for it in the log
![log-no-taboola](https://user-images.githubusercontent.com/2706662/50230232-429d2880-037a-11e9-93c4-149b25d938c5.PNG)
6.  Restored settings
7.  Visited the slate site. Taboola does not load, again no requests in the log.

So whatever the bug is, it's not reproducible with 1.3.15.101

Should I repeat with 1.3.14?

**Comment by jrynd** [comment] 2018-12-19 15:44
I just noticed that it wasn't only taboola, I'd also forbidden a bunch of other ad networks as you can see in the shot of the matrix, that all got to load according to the log.

**Comment by uBlock-user** [comment] 2018-12-19 16:36
Probably requires a combination of of Chrome version 71 and 1.13.14, I'm on the dev build, so none of them could reproduce.

**Closed** 2018-12-29 21:02 UTC
Labels: unable to reproduce

**Comment by jrynd** [comment] 2019-02-20 14:46
Hi, this issue seems to be back.
Windows 10
Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)
UMatrix Development Build 1.3.17.1

Images clearly are loading from images.taboola.com, but images.taboola.com does not show up in the umatrix as a host.

Do you want more logs? Screenshots?
![taboola2019](https://user-images.githubusercontent.com/2706662/53099737-6274d800-34f4-11e9-8827-4ed3dfbfac1f.PNG)

**Comment by jrynd** [comment] 2019-02-20 16:42
Also https://www.washingtonpost.com/politics/courts_law/supreme-court-says-constitutional-protection-against-excessive-fines-applies-to-state-actions/2019/02/20/204ce0d4-3522-11e9-af5b-b51b7ff322e9_story.html

I looked in the log and images.taboola.com is not shown. The image is being loaded without umatrix even knowing about it.

**Comment by gorhill** [comment] 2019-02-20 17:01
See <https://twitter.com/gorhill/status/1097481139294519297>, this applies to all content blockers.

**Comment by jrynd** [comment] 2019-02-20 20:08
Wait, you're saying that umatrix on chrome is no longer supported?

**Comment by jrynd** [comment] 2019-02-22 19:33
Thanks!
