### ISSUE TITLE
behind-the-scene broken at gmail

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uMatrix-issues#62] opened 2018-09-24 07:44 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

On gmail, behind-the-scene requests are blocked unconditionally and th refresh button on the for behind-the-scene panel doesn't work. BTS Refresh button broke with v1.3.0 and BTS network requests are being blocked unconditionally since 1.3.8.
 
### A specific URL where the issue occurs

`https://mail.google.com/mail/u/0/?tab=wm#inbox`

### Steps to Reproduce

1. Disable ALL extensions and install uMatrix from https://github.com/gorhill/uMatrix/releases/tag/1.3.15b2

2. Once installed, visit gmail and login with your credentials

3. Open the logger and refresh the page to populate, once loaded, page will appear broken, because _behind-the-scene_ network requests are being [blocked unconditionally](https://i.gyazo.com/74f734766ab22c27b74af9517f0444cb.png). even though it's default installation where matrix is set to off for _behind-the-scene_.

4) Click on a behind-the-scene network request to open up behind-the-scene popup panel and now click on the refresh button, the tab doesn't refresh.

### Supporting evidence

Errors collected via Chromium on v1.3.0 regarding the refresh button issue - ![](https://i.gyazo.com/53f21a9513fad79038fd6bf22762c7ab.png)

Broken refresh button at BTS panel and BTS network requests being blocked unconditionally - 

https://i.gyazo.com/014e222d6d50f97d57c3d66869f0b0c8.mp4

### Your environment

* uMatrix version: 1.13.15.2
* Browser Name and version: Chromium 71
* Operating System and version: Win 10 x64

**Comment by uBlock-user** [comment] 2018-09-24 08:07
Because of this, gmail remains broken for me as in I can't use funcionality such as Add to Drive and download attachments etc.. until I disable this extension from Extensions page. Seems to be happening with Firefox. Let me know if you're unable to reproduce.

**Comment by uBlock-user** [comment] 2018-09-24 10:37
> Of course, "behind-the-scene" means there is no specific tab associated with the request, hence there no tab for uMatrix to refresh. This is not new behavior, this has always been the case.

So why does v1.3.0/4/6 spew errors like this - 

![](https://camo.githubusercontent.com/32ae6e45d0f48b1597b217a06999dc880fae1c66/68747470733a2f2f692e6779617a6f2e636f6d2f35336632316139353133666164373930333866643662663232373632633761622e706e67)

> what exactly is broken with screenshots

BTS requests are bring blocked unconditionally on my end, because of this, gmail remains broken for me as in I can't use funcionality such as Add to Drive and download attachments/images don't load etc..

> I only have a "dont-care" Gmail account for testing purpose, and I logged in into it without issue and I could not spot anything broken. I don't have emails with attachment in it or even a Google Drive account

I feared this would happen, I posted all the information I could gather here, don't know what else I could give you.

**Comment by uBlock-user** [comment] 2018-09-24 10:39
I could e-mail you a dummy pdf on your gmail account if you want.

**Comment by gorhill** [comment] 2018-09-24 10:54
> So why does v1.3.0/4/6 spew errors like this

I don't get that with latest uMatrix. I can't say it didn't happen with 1.3.0, but that is an old version, you shouldn't be reporting issue with older versions unless they also occur in current stable.

**Comment by uBlock-user** [comment] 2018-09-24 10:59
The reason I'm reporting from that version is because the latest dev build doesn't throw such StackTrace errors even though when refresh button is clickedfrom BTS panel, but only v 1.3.0/4/6 do.

**Comment by uBlock-user** [comment] 2018-09-24 11:03
console errors if they help any - 

![](https://i.gyazo.com/a1b51a5551831488b31242abd3341273.png)

![](https://i.gyazo.com/414c7496abe9ba79facc625b26d77a33.png)

**Comment by gorhill** [comment] 2018-09-24 11:05
> the latest dev build doesn't throw such StackTrace

Because the issue is no longer present? That was my point: why report issues from past versions which no longer exist in the latest stable release. This was probably fixed in 1.3.8.

**Comment by uBlock-user** [comment] 2018-09-24 11:07
OK, but what about those BTS requests being blocked unconditionally ?

**Comment by gorhill** [comment] 2018-09-24 11:08
This is the ruleset I have when trying to reproduce:

```
https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
google.com gstatic.com * allow
```

What about yours?

**Comment by uBlock-user** [comment] 2018-09-24 11:10
same as yours on default rule set

![](https://i.gyazo.com/3c6b139cf8397fb6b513a29761d9b34e.png)

**Comment by gorhill** [comment] 2018-09-24 11:13
Don't you need to set `google.com gstatic.com * allow`? I needed this.

**Comment by gorhill** [comment] 2018-09-24 11:29
Send me something at: `uKOeoIfHQDp8 [at] gmail [dot] com`. I will delete this message once you confirm doing so.

**Comment by uBlock-user** [comment] 2018-09-24 11:31
Done. Sent my regular ruleset alongwith.

**Comment by gorhill** [comment] 2018-09-24 11:35
I could open your attachments, and also download locally, but the later required me to add `google.com googleusercontent.com frame allow` from the popup panel.

**Comment by uBlock-user** [comment] 2018-09-24 11:37
With `mail.google.com gstatic.com script allow` the images and thumbnails remain broken,

With `mail.google.com gstatic.com * allow` , the above issue is solved.

**Comment by uBlock-user** [comment] 2018-09-24 11:41
Another thing `mail.google.com gstatic.com * allow` doesn't fix the Save To Drive functionality which is still broken.

**Comment by gorhill** [comment] 2018-09-24 11:54
I could "Save to Drive" fine. However the "Save to Drive" popup was blank, I fixed by adding the following rules:

    mail.google.com content.googleapis.com * allow
    mail.google.com googleusercontent.com * allow

The first one might not be needed, it's the one I tried first.

**Comment by uBlock-user** [comment] 2018-09-24 12:02
I don't get any popups, I click and it goes into an infinite loop of Saving to Drive...it's fine I will figure that one out.

Since I don't wanna whitelist the entire gstatic.com on mail.google.com, so I narrowed it down to

```
mail.google.com ssl.gstatic.com xhr allow
mail.google.com www.gstatic.com xhr allow
```

These two rules bring back the broken images and thumbnails, but weird thing is there's no XHR being made from those rules or atleast a number doesn't appear on those cells

![](https://i.gyazo.com/314c48ac96679316dd7828ea9e93c7b7.png)

**Comment by gorhill** [comment] 2018-09-24 12:05
As per your per-site switch count, you are blocking workers -- I didn't see this in your ruleset screenshot above. Gmail does use workers.

**Comment by uBlock-user** [comment] 2018-09-24 12:05
Okay so XHRs re coming from those `ssl.gstatic.com` and `www.gstatic.com` but those are behind-the-scene requests, and since BTS is already whitelisted, I shouldn't need to add 

```
mail.google.com ssl.gstatic.com xhr allow
mail.google.com www.gstatic.com xhr allow
```

Right ?

**Comment by uBlock-user** [comment] 2018-09-24 12:07
No workers appear blocked on my end

![](https://i.gyazo.com/dfef495c88afe2214bc6a697835534ff.png)

**Comment by uBlock-user** [comment] 2018-09-24 12:12
@gorhill If I don't add 

```
mail.google.com ssl.gstatic.com xhr allow
mail.google.com www.gstatic.com xhr allow
```

BTS XHRs get blocked, why is that, why does BTS is getting affected by those rules ?

**Comment by gorhill** [comment] 2018-09-24 12:14
Well you opened this issue a few months ago: <https://github.com/uBlockOrigin/uMatrix-issues/issues/22>.

**Comment by gorhill** [comment] 2018-09-24 12:16
> BTS XHRs get blocked, why is that, why does BTS is getting affected by those rules ?

I can't remember where but we talked about how "behind-the-scene" changed in uMatrix: not all entries marked as "behind-the-scene" are real actual behind-the-scene, because now uMatrix makes use of initiator if present to filter request, and when the initiator is present, the logger still report the request as behind the scene -- I just miss the time to overhaul the logger to now account for this. This is also true for uBO.

**Comment by uBlock-user** [comment] 2018-09-24 12:17
I disabled all th 4 switches and still no change, so it's not the same, BTS XHRs are getting blocked regardless of workers switch enabled or not.

**Comment by uBlock-user** [comment] 2018-09-24 12:18
> I can't remember where but we talked about how "behind-the-scene" changed in uMatrix: not all entries marked as "behind-the-scene" are real actual behind-the-scene, because now uMatrix makes use of initiator if present to filter request, and when the initiator is present, the logger still report the request as behind the scene -- there is still no specific tab involved, but there is a specific origin, as opposed to real behind-the-scene where there is no tab and no origin.

I think you nailed it there. That's only makes logical sense.

**Comment by gorhill** [comment] 2018-09-24 12:19
You could use uBO's logger just to find out the context in which these XHRs are made (uMatrix does not have this information in the logger yet). For the target XHRs, click the cell to create filters in uBO's logger, the context will be shown.

**Comment by uBlock-user** [comment] 2018-09-24 12:27
No wonder I got trolled by the extension, since it kept telling me about BTS, when it wasn't at all. 

So should this be closed or do you wanna keep this issue open ?

**Comment by gorhill** [comment] 2018-09-24 12:28
>     mail.google.com ssl.gstatic.com xhr allow
>     mail.google.com www.gstatic.com xhr allow

If you need to add these, than this probably means they are made by the worker, which origin is `mail.google.com`. I mentioned earlier, I had `google.com gstatic.com * allow` set in order for me to log in into Gmail -- and this rule would also cause the two above rules to be unnecessary -- hence maybe why all worked fine on my side.

Bottomline is that I need to revisit the logger to account for this kind of issue and the one reported at <https://github.com/gorhill/uMatrix/issues/951>: the popup-panel-from-the-logger is the wrong approach, the logger just need a very simple UI to set rules for `source destination type` from any row, behind the scene or not.

**Comment by gorhill** [comment] 2018-09-24 12:30
Keep it opened, it clearly remind me how important I need to fix the logger in uMatrix.

**Comment by uBlock-user** [comment] 2018-09-24 12:32
What about uBO's logger, even though it shows the correct context, it still shows the request as BTS ?

**Comment by uBlock-user** [comment] 2018-09-24 13:28
I meant do you intend to fix uBO's logger regarding this issue ?

**Comment by gorhill** [comment] 2018-09-24 13:36
https://github.com/gorhill/uBlock/issues/3654#issuecomment-377803278

**Comment by gorhill** [comment] 2018-09-29 11:27
A column has been added to the logger: the scope in which network requests are made. Thus, the behind-the-scene scope is now shown just like any other scope: `behind-the-scene`. The block/allow column is clickable and must be use to set rules specific strictly to the entry.

**Comment by uBlock-user** [comment] 2018-10-03 10:50
Still doesn't show number of requests on XHR matrix cell, so the user still won't know which cell to whitelist for stop breakage,

**Comment by gorhill** [comment] 2018-10-03 11:17
Can you provide a screenshot of what you are seeing? If a request is shown as `behind-the-scene`, than it is really behind-the-scene.

**Comment by gorhill** [comment] 2018-10-03 11:44
The fix was in the logger -- you should be able to see in the logger these requests. uMatrix is not reporting them in the popup panel of that tab probably because there is no tab information provided for these specific requests. In such case, the logger is where ultimately those problems are resolved, hence the new UI in the logger.

**Comment by uBlock-user** [comment] 2018-10-03 11:50
> uMatrix is not reporting them in the popup panel of that tab probably because there is no tab information provided for these specific requests.

Can anything be done about this ?

**Comment by uBlock-user** [comment] 2018-10-10 14:29
Thanks to this new UI, asset updates on Firefox are initiated by `moz-extension-scheme` and on Chromium it's `chrome-extension-scheme`, those who disable uMatrix on both these schemes won't be affected, but thought I would post for those like me who go with whitelist and blocking the rest, due to this change, the [BTS popup panel](https://i.gyazo.com/02ef515618d2cfb3f79aaf5885b99981.png) is misleading and is required to be removed FYI.

**Comment by gorhill** [comment] 2018-10-16 14:06
I will need to provide access to the per-scope switches from the new per-entry rule editor UI.

**Comment by uBlock-user** [comment] 2018-12-25 08:11
Update -

On Chromium - 

![](https://i.gyazo.com/75d1f07d83922fecc5690216b9ac12e0.png)

On Firefox - 

![](https://i.gyazo.com/e1f2e46c393a24d13a0de86ebea5cace.png)

Notice the XHR cell count doesn't appear on Chromium's dev build.

**Comment by gwarser** [comment] 2018-12-25 12:36
In Chromium service worker loads all gstatic XHRs using tab-less mail.google.com context.

In Firefox they are not tab-less.

**Comment by uBlock-user** [comment] 2018-12-25 12:45
Tabless requests should also be shown in the main popup UI to combat this. The cell count number not appearing is really troubling.

**Closed** 2019-03-03 08:57 UTC
Labels: bug, fixed
