### ISSUE TITLE
hpHosts will no longer be updated

### ISSUE THREAD

**Issue by Vixavaguba** [uBlockOrigin/uMatrix-issues#247] opened 2020-04-11 19:34 UTC
### Prerequisites

- [] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

<hpHosts will no longer be updated>

### A specific URL where the issue occurs
See details on: 
<https://www.reddit.com/r/uBlockOrigin/comments/fsgy4b/hphosts_ad_and_tracking_servers_link_down/>

and further statement of site owner(?) here:
<https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?do=findComment&comment=1370008>

### Steps to Reproduce

1. [Tab: Assets]
2. [hpHosts’ Ad and tracking servers]
3. [try to update the blacklisted servers]
4. [Notice that the a.m. does no longer update at all even if tried several times in a row]

### Ruleset

<not necessary>

### Supporting evidence

<Assets: see hpHosts’ Ad and tracking servers and check / uncheck corresponding box and try to update>

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox 60.9.0esr (64-Bit)
* Operating System and version: Windows 7 Ultimate 64-Bit

**Comment by uBlock-user** [comment] 2020-04-11 19:38
Duplicate of #223

**Closed by uBlock-user** 2020-04-11 19:38 UTC
