### ISSUE TITLE
uMatrix sometimes doesn't show third party domain entries in the matrix selector on Firefox Android

### ISSUE THREAD

**Issue by edgargerad** [uBlockOrigin/uMatrix-issues#146] opened 2019-05-05 21:19 UTC
### Prerequisites

- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x ] uMatrix is the only extension
    - [ x] uMatrix with default lists/settings
    - [x ] using a new, unmodified browser profile
- [ x] I am running the latest version of uMatrix
- [ x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When going to the umatrix selection page with uMatrix 1.3.16 on Firefox Android 66.0.2, the selector sometimes doesn't display third-party domains and only displays first-party domains.
### A specific URL where the issue occurs
https://github.com/uBlockOrigin/uMatrix-issues

### Steps to Reproduce

1. Go to https://github.com/uBlockOrigin/uMatrix-issues
2. Open the umatrix selector page
3. Only GitHub.com entries are shown.  There should be githubassets.com entries shown as well, but they sometimes do not display.

### Ruleset

This happens with a new install using a default ruleset.
### Supporting evidence
![Screenshot_20190505-171333](https://user-images.githubusercontent.com/50304563/57200421-d5b9b200-6f59-11e9-8a28-70c09a9f0a00.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox Android 66.0.2
* Operating System and version: Android 9.0 (running on a Motorola Moto G7)

**Comment by uBlock-user** [comment] 2019-05-05 21:24
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/132

**Closed by uBlock-user** 2019-05-05 21:24 UTC

**Comment by gwarser** [comment] 2019-05-05 21:25
On Android this is probably https://github.com/uBlockOrigin/uMatrix-issues/issues/95
