### ISSUE TITLE
Update content of the matrix when switching tabs

### ISSUE THREAD

**Issue by RadoQS** [uBlockOrigin/uMatrix-issues#107] opened 2019-02-01 18:25 UTC
### Prerequisites

- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [ ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uMatrix
- [x ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Usability enhancement:
I start out "all blocked", so I have to use µM quite a lot. It happens that I want to have/ keep it open on several tabs at a time. When I switch back & forth between tabs, the µMcontent is "sticky", it doesn't reflect the content of the viewed tab, but the one where it was opened.
I have to be careful where I'm in, what I'm looking at, or else keep closing/ opening µM each time I switch.

However, the object-counter on the icon _does_ change according to the tab.

### Steps to Reproduce

1. Go to any site in 1 tab, open µM for it.
2. Go to another site 2 on another tab.
3. µM content displays rules for site 1, while the counter on the icon changes for site 2.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: FF 60.4.0.esr
* Operating System and version: win10

**Comment by uBlock-user** [comment] 2019-02-01 18:32
> µM content displays rules for site 1, while the counter on the icon changes for site 2.

tested on Chromium/Firefox both, working as expected.

**Comment by gorhill** [comment] 2019-02-01 18:43
Don't say "site 1", "site 2", provide actual URLs so that we can compare the results on each side.

**Comment by uBlock-user** [comment] 2019-02-02 07:15
> FF GUI issue

could be specific to v60 then as I do not experience this on Nightly..

**Comment by gwarser** [comment] 2019-02-02 13:10
How you managed to keep matrix opened after you click somewhere else? I cannot do this. I tried in ESR and cannot reproduce, because uM popup closes immediately after loosing focus.

**Comment by uBlock-user** [comment] 2019-02-02 13:53
@RadoQS Did you mean like this -- 

![](https://i.gyazo.com/eec69565a80683f57e93a56bc070d80c.png) 

?

**Comment by uBlock-user** [comment] 2019-02-02 13:59
If I open the popup panel in a new tab, and browse to a website in another tab, uMatrix's popup panel will get updated, but if I open popup panel in new window, it will not get updated, this is browser behaviour, not a uMatrix bug.

**Comment by gorhill** [comment] 2019-02-02 14:14
> if I open popup panel in new window

How do you do this?

**Comment by uBlock-user** [comment] 2019-02-02 14:19
Click on the extension icon to open popup panel > right click on the black bar > Open in a new window.

**Comment by uBlock-user** [comment] 2019-02-02 14:31
uBO's black bar is not clickable anymore, I believe that behaviour is also a TODO for uMatrix.

**Comment by uBlock-user** [comment] 2019-02-02 14:35
In case of uBO, if you open dashboard in a new tab, it won't get updated either and wit act as a permanent view, just like opening in a new Window.

**Comment by gorhill** [comment] 2019-02-02 14:36
You can use ctrl-shift-click the "all" cell in uBO to open the popup panel in its own tab. You will get the same behavior as here -- I won't change this neither here or with uBO. One can open as many popup panel-in-a-wndow as they chose, each will be bound to a specific tab.

**Comment by gorhill** [comment] 2019-02-02 14:39
Closing as "by design".

**Closed by gorhill** 2019-02-02 14:39 UTC

**Comment by uBlock-user** [comment] 2019-02-02 14:40
Shall this be closed as wontfix ?

**Comment by RadoQS** [comment] 2019-02-07 19:07
Sorry for getting so late back to this:
@gwarser: no idea, for me the pop-up just sticks, I must hit ESC to make it disappear. If you have an idea what influences this, then I'd be really happy to know. I can provide a video if it helps (where to upload?).

@uBlock-user: your screenshot looks like µM is the content of a separate tab, that's not what I experience here. For me it's just a pop-up just below the µM icon/indicator, covering the top-right corner of the tab content (and it's sticky), where all the mismatch happens.

Sounds like gorhill's "follow current active tab" working in uBO is what I'm looking for, so I'll be patient until it finds its way to µM.
It would be nice to easily switch between tabs (with ctrl-pgup/dn) with the pop-up matrix open to quickly adjust the cells without having to open/close it each time.

Thank you for your efforts for producing µM & its service.

**Comment by RadoQS** [comment] 2019-02-13 19:03
@gwarser: I found out why it sticks:
user_pref("ui.popup.disable_autohide", true);
