### ISSUE TITLE
uMatrix has missing domains and shows wrong domains

### ISSUE THREAD

**Issue by baptx** [uBlockOrigin/uMatrix-issues#21] opened 2018-06-12 09:30 UTC
### Prerequisites

* [x] Did you perform a cursory search of the issue tracker?
* Can you reproduce the problem when...
    * [ ] uMatrix is the only extension?
    * [ ] uMatrix with default lists/settings?
    * [ ] using a new, unmodified browser profile?
    * [x] not sure, I can't reproduce the problem easily, it happens randomly
* [x] Are you running the latest version?
* [x] Did you check the [documentation](https://github.com/gorhill/uMatrix/wiki)?

### Description

Sometimes uMatrix has missing third-party domains and sometimes it shows wrong third-party domains that I had open in another tab. I noticed that the problem happened when I had a new tab open and it disappeared when I drag-and-dropped a tab in Firefox to make it a new window instead.

### A specific URL where the issue occurs

It happened on a page like https://www.prizle.com/fr/inscription but can happen on other websites.

### Steps to Reproduce

To be defined. Random at the moment.

### Supporting evidence

Screenshots: https://www.reddit.com/r/uMatrix/comments/8q9jlk/umatrix_has_missing_domains_and_shows_wrong/

### Your environment

* uMatrix version: 1.3.8
* Browser Name and version: Firefox 60.0.1
* Operating System and version: Xubuntu 16.04.4 LTS

**Comment by gorhill** [comment] 2018-06-12 10:34
For the missing entries, the browser can bypass uMatrix listeners when it pulls requests from its short-term cache, nothing uMatrix can do around this.

For the extra entries, this can happens when pages are designed in a way which causes network request to be fired after navigating away from the page -- for example when a page fires a `navigator.sendBeacon()` request in an `beforeunload` listener.

**Comment by uBlock-user** [comment] 2018-06-12 10:48
@gorhill Duplicate of https://github.com/gorhill/uMatrix/issues/221 ??

**Comment by gorhill** [comment] 2018-06-12 11:20
Yes, for the extra entries it's duplicate of #221.

**Comment by uBlock-user** [comment] 2018-06-12 11:22
Duplicate of https://github.com/gorhill/uMatrix/issues/221

**Closed by uBlock-user** 2018-06-12 11:22 UTC

**Comment by uBlock-user** [comment] 2018-06-12 11:42
You did mention `documentUrl` in https://github.com/gorhill/uBlock/issues/3693 and https://github.com/gorhill/uBlock/issues/3546 although can't find anything about it in uMatrix's repo.

**Comment by baptx** [comment] 2018-06-13 17:31
Any idea how these problems are prevented by other similar addons like RequestPolicy? I don't remember having seen these problems when I was using RequestPolicy until the addon was not compatible with Firefox Quantum.
By the way, the README file from https://github.com/gorhill/uMatrix could be updated to say that users can create issues in this repository. I did not know there was a specific file https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md for this. Updating the README could prevent users from posting bugs on Reddit like I did and and it will help users finding known issues on this repository.

**Comment by joveian** [comment] 2018-08-29 18:57
Maybe I'm the only one foolish enough to try this, but I've seen missing domains with Firefox Tracking Protection enabled.  It doesn't always show the shield icon and disabling via the shield icon does not always fix it but globally disabling tracking protection does fix it.  I added a note to the "the page is still broken after I created all necessary rules" page.

**Comment by baptx** [comment] 2019-05-07 16:01
The issue happens everytime on a website like https://atomik-tour.org/, the request to load the iframe https://umap.openstreetmap.fr/en/map/atomik-tour-2019_262457?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false%22#6/46.717/2.285 is blocked and we cannot allow the request though uMatrix addon.
It looks like the cache bypass workaround described by @gorhill is not working (I tried shortcut Ctrl+Shift+R to reload the page without cache). Is there another workaround or a fix planned soon?

**Comment by baptx** [comment] 2020-08-17 10:45
I had the missing domain again with the Google Maps integration of a page like https://www.huffingtonpost.fr/entry/covid-19-ces-villes-et-marches-ou-le-masque-est-obligatoire-en-exterieur_fr_5f1fd651c5b638cfec494f52. The workaround was to navigate to another page and then open the page again (without using the browser back button but for example by using Ctrl+Z in the URL bar to open the previous URL directly).
