### ISSUE TITLE
Multiple Redirects Fail

### ISSUE THREAD

**Issue by aerogems** [uBlockOrigin/uMatrix-issues#53] opened 2018-09-13 20:24 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Links with multiple redirects in Firefox stop working on the second redirect. Clicking the uMatrix reload button will not allow the browser to move on to the next redirected page. User must close the tab and reopen, then temporarily allow domain again before reloading.

### Steps to Reproduce

1. Click on "Newegg" link in URL above
2. Temporarily allow the first redirected domain and reload the page
3. Temporarily allow the second redirected domain and attempt to reload the page

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: Firefox 63b4, but I have witnessed this same effect on multiple versions of Firefox, both stable and beta. I also used uMatrix on Chromium (Vivaldi) for some time and never witnessed this issue.
* Operating System and version: Windows 10 1803 (10.0.17134.285)

**Comment by gwarser** [comment] 2018-09-13 20:49
Cannot reproduce, your link is dynamic:

1:

- click on `slickdeals.net` link
- uMatrix has prevented the following page from loading...
- click on `url = https://www.newegg.com/Product/Product.aspx?sdtid=12034123&SID=0f5a2c...`
- end on Acronis True Image page

2:

- click on `slickdeals.net` link
- `cj.dotomi.com` - "The website you just visited provides you with access to products..."
- "Continue to site" button
- end on Acronis True Image page

**Comment by aerogems** [comment] 2018-09-13 21:13
Let me see if I can be more clear.

From slickdeals.net link:

1. Click on Newegg link
2. Arrive at cj.dotomi.com which is blocked by uMatrix
3. Open uMatrix and temporarily allow cj.dotomi.com domain
4. Reload page using uMatrix reload button
5. Arrive at second domain blocked by uMatrix
6. Open uMatrix and temporarily allow new domain
7. Reload page using uMatrix reload button or main Firefox reload button
8. With Chromium browsers, page will reload and new temporary rules will be parsed; with Firefox, page appears to reload, but new temporary rules are not parsed/honored

Admittedly I have clearly been overthinking my use of uMatrix and could have just been clicking on the link in the blocked page rather than temporarily allowing a domain, but the behavior between the Chrome and Firefox versions of uMatrix is still different.

**Comment by uBlock-user** [comment] 2018-09-14 01:53
`https://slickdeals.net/?adobeRef=cf6109acb79011e8a9062211e560f7e80000&pno=419771&lno=1&sdtid=12034123&trd=Newegg%2Bcom&afsrc=1`  leads to 

`http://www.tkqlhce.com/click-1225267-10446076?sid=7a3ca262b7c011e8a66da644d253a3840INT&url=https%3A%2F%2Fwww.newegg.com%2FProduct%2FProduct.aspx%3Fsdtid%3D12034123%26SID%3D7a3ca262b7c011e8a66da644d253a3840INT%26AID%3D10446076%26PID%3D1225267%26nm_mc%3DAFC-C8Junction%26cm_mmc%3DAFC-C8Junction-Slickdeals%2520LLC-_-na-_-na-_-na%26Item%3DN82E16832200141` which in turn leads to

`http://cj.dotomi.com/4a111ft10J/t-4/IHLLNHON/IJJMJNO/H/H/H?t=sxni%3DCf8hf7B7gCh566jDfBBifB99i7A8f8D95NSY%26zwq%3Dmyyux%258F%257K%257K111.sj1jll.htr%257KUwtizhy%257KUwtizhy.fxu2%258Kxiyni%258I67589678%257BXNI%258ICf8hf7B7gCh566jDfBBifB99i7A8f8D95NSY%257BFNI%258I6599B5CB%257BUNI%258I677A7BC%257Bsr_rh%258IFKH-HDOzshynts%257Bhr_rrh%258IFKH-HDOzshynts-Xqnhpijfqx%257A75QQH-_-sf-_-sf-_-sf%257BNyjr%258ISD7J6BD87755696%3c%3cmyyu%3A%2F%2F111.ypvqmhj.htr%3AD5%2Fhqnhp-677A7BC-6599B5CB%3c%3cL%3c%3c%3c6%3c6%3c-6%3c6%3c5%3c` which inturns leads to

`http://www.emjcd.com/32100vpyxH/pw0/EDHHJDKJ/EFFIFJK/D/LIFGDHIMDGKJDHDKKJ:oF61vvYgOMKF/MnrFMrqEoKpDEErLLEIFDFqrDnELDIDo?i=yI83%3DX0T20SWS1X2QRR4Y0WW30WUU3SVT0TYUQint%26KHB%3D7JJFI%25Ta%25Sf%25SfMMM.D4M466.2EC%25SfpHE3K2J%25SfpHE3K2J.0IFN%25TfI3J83%25TdRSQTURST%25SWsid%25TdX0T20SWS1X2QRR4Y0WW30WUU3SVT0TYUQint%25SWaid%25TdRQUUWQXW%25SWpid%25TdRSSVSWX%25SWDC_C2%25Tdafc-cYjKD2J8ED%25SW2C_CC2%25Tdafc-cYjKD2J8ED-sB82A340BI%25SVSQllc-_-D0-_-D0-_-D0%25SWiJ4C%25TdnYSeRWYTSSQQRUR%3c29E!MWFC-M5OSMO8%3c7JJF%3A%2F%2FMMM.JAGB724.2EC%3AYQ%2F2B82A-RSSVSWX-RQUUWQXW%3c%3cg%3c%3cTS124Y21-XW13-U0S2-ZRSZ-TUUZR21W1X3Y%3cR%3cR%3c-R%3cR%3cQ%3c` which ultimately leads to

Acronis True Image 2018 - 3 Device page - `https://www.newegg.com/Product/Product.aspx?sdtid=12034123&SID=7a3ca262b7c011e8a66da644d253a3840INT&AID=10446076&PID=1225267&nm_mc=AFC-C8Junction&cm_mmc=AFC-C8Junction-Slickdeals%20LLC-_-na-_-na-_-na&Item=N82E16832200141&cm_sp=`

Nothing's wrong with uMatrix and nothing to do with it either except for the part where it blocks these domains as per the entries in HOSTS file, these redirects themselves are server-sided.

**Comment by uBlock-user** [comment] 2018-09-14 01:58
> with Firefox, page appears to reload, but new temporary rules are not parsed/honored

They're, I cannot reproduce either. For me, the behaviour is same as Chromium browsers.

**Comment by gwarser** [comment] 2018-09-14 06:41
- open link `https://slickdeals.net/?adobeRef=cf6109acb79011e8a9062211e560f7e80000&pno=419771&lno=1&sdtid=12034123&trd=Newegg%2Bcom&afsrc=1`
- uMatrix has prevented... 
- scope is `tkqlhce.com` from `www.tkqlhce.com`
- make green `www.tkqlhce.com` and reload without closing matrix
- scope is `com` from `cj.dotomi.com`
- make green `cj.dotomi.com` and `dotomi.com`, reload without closing matrix
- nothing happens

If I close matrix, scope changes from `com` to `dotomi.com` and after couple more reloads (`emjdc.com`) I arrive on "acronis" page. Manually narrowing scope also helps.

**Comment by gorhill** [comment] 2018-09-14 09:33
I can reproduce with @gwarser steps.

This happens if we keep the popup panel opens between reload -- this is a popup panel issue, it seems there is an issue updating the content of the panel when the scope changes such that an improper scope is selected in the panel after a page reload.

**Comment by uBlock-user** [comment] 2018-09-14 09:38
This happens in Chromium too.

**Closed** 2018-09-14 10:45 UTC
Labels: bug
