### ISSUE TITLE
Unable to scroll horizontally on desktop Firefox

### ISSUE THREAD

**Issue by cbcoutinho** [uBlockOrigin/uMatrix-issues#41] opened 2018-08-06 13:35 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - it seems this issue has been previously reported on the deprecated issue tracker (gorhill/uMatrix#656, gorhill/uMatrix#828), but i'm not sure if those are mobile issues or not.
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox 61.0.1 (64-bit)
Windows 10
uMatrix 1.3.12

The uMatrix banner is being cut off on the right with no option to scroll horizontally

### A specific URL where the issue occurs

URL from screenshot below, no zoom used:

https://www.strongtowns.org/journal/2013/3/4/the-stroad.html

### Steps to Reproduce

There is no scroll bar, so there isn't anything to reproduce.

### Supporting evidence

![image](https://user-images.githubusercontent.com/12901868/43719343-bbb56f22-998d-11e8-89e0-8a31520ba531.png)

**Comment by gorhill** [comment] 2018-08-06 13:40
https://github.com/gorhill/uMatrix/issues/811

**Comment by cbcoutinho** [comment] 2018-08-06 13:44
Okay thanks for the link, feel free to close

**Comment by uBlock-user** [comment] 2018-08-06 14:08
Duplicate of https://github.com/gorhill/uMatrix/issues/811

**Closed by uBlock-user** 2018-08-06 14:08 UTC
