### ISSUE TITLE
Filter also by url path, not just subdomains

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [uBlockOrigin/uMatrix-issues#271] opened 2020-06-19 13:42 UTC
### Prerequisites

- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X ] uMatrix is the only extension
    - [X ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X] I am running the latest version of uMatrix
- [ X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Some website have various services subdivided not just by subdomains, but also by url path (subfolders). And the JS loads differentially for the top domain and the subfolders in path. Current functionality does not allow for this. Is this easy to implement?

### A specific URL where the issue occurs

Any website with url path that includes subfolders such as website.com/news

### Steps to Reproduce

1. Try setting different filtering rules on website.com and on website.com/news
2. [Second Step]
3. [and so on...]

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox 77
* Operating System and version: Ubuntu 20

**Comment by uBlock-user** [comment] 2020-06-19 13:45
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/217

**Closed by uBlock-user** 2020-06-19 13:45 UTC
