### ISSUE TITLE
How to install uMatrix on Firefox 56 after certificate problem on 2019-05-05?

### ISSUE THREAD

**Issue by Aybee** [uBlockOrigin/uMatrix-issues#147] opened 2019-05-06 11:52 UTC
### Prerequisites

- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uMatrix
- [x ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

After the certificate problem now uMatrix runs again on Firefox 66. But not on Firefox 56. I know it's not a uMatrix error, but does someone knows the trick to get extensions running after the Firefox problem?

### Steps to Reproduce

1. Install FF 56
2. Try to install an extension like uMatrix

### Your environment

* uMatrix version: 1.3.8
* Browser Name and version: Firefox 56
* Operating System and version: Windows 10 Home

**Comment by gorhill** [comment] 2019-05-06 12:51
Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/144>.

**Closed by gorhill** 2019-05-06 12:51 UTC
Labels: duplicate

**Comment by Remu-rin** [comment] 2019-05-07 01:17
> After the certificate problem now uMatrix runs again on Firefox 66. But not on Firefox 56. I know it's not a uMatrix error, but does someone knows the trick to get extensions running after the Firefox problem?

https://www.reddit.com/r/firefox/comments/bkspmk/addons_fix_for_5602_older/

**Comment by Aybee** [comment] 2019-05-07 11:09
@remu Thank you so much. This realy worked like a charme. Very nice find.
🥇 👏 👍 

@gorhill This is not really a duplicate, as in #144 FF56 is not mentioned. This issue is espacially for FF56 😏

**Comment by uBlock-user** [comment] 2019-05-07 11:38
> FF56 is not mentioned

version doesn't matter as all variants of Firefox are affected.

**Comment by gorhill** [comment] 2019-05-07 12:00
The issue is not with uBO, there is nothing to fix in uBO -- the issue is with Firefox and this is where you need to find support, <https://bugzilla.mozilla.org/show_bug.cgi?id=1549078#c55>.

Firefox 56 is no longer supported by Mozilla, you should move to Firefox 60 ESR.

**Comment by gorhill** [comment] 2019-05-14 15:16
https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-52-56/
