### ISSUE TITLE
Spoof referrer will break cross-origin-request (CORS) protected sites

### ISSUE THREAD

**Issue by FearNaBoinne** [uBlockOrigin/uMatrix-issues#20] opened 2018-06-12 08:14 UTC
### Description

Spoof referrer will break cross-origin-request (CORS) protected sites, like for instance Facebook video's played embedded in the main site...

### A specific URL where the issue occurs

https://www.facebook.com/TheMuscleCars/videos/342151062918342/

### Steps to Reproduce

1) Enable Referrer Spoofing for 3rd party requests
2) go to above facebook vid
3) Open Web Console
4) See CORS errors
5) Press Play
6) Watch site reload and repeat same CORS error

### Supporting evidence

From Web Consoler when spoofing is enabled:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://video-amt2-1.xx.fbcdn.net/v/t42.1790-2/25447010_1170848543048005_1041484747001298944_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfcGFzc3Rocm91Z2hfZnJhZ18yX3ZpZGVvIn0%3D&oh=3115624a6c3f1d128adf2a9d68c70603&oe=5B1FB1DA&bytestart=935&byteend=1386. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://video-amt2-1.xx.fbcdn.net/v/t42.1790-2/25207412_542886392755863_8670442345214246912_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfcGFzc3Rocm91Z2hfZnJhZ18yX2F1ZGlvIn0%3D&oh=e4f45483ba5ac1756d0b910a98e090a7&oe=5B1FAA1B&bytestart=874&byteend=1469. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Invalid URI. Load of media resource  failed.

### Your environment

* uMatrix version: 1.3.10
* Browser Name and version: FireFox 60.0.2
* Operating System and version: MacOs High Sierra 10.13.5

**Comment by gwarser** [comment] 2018-06-12 10:17
Why you think it's uMatrix issue? Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/19

**Comment by gwarser** [comment] 2018-06-12 10:35
This has been discussed before https://github.com/gorhill/uMatrix/issues/358
Spoofing origin should be disabled - no idea why this not work again.

**Closed** 2018-06-12 10:36 UTC
Labels: duplicate, invalid

**Comment by gwarser** [comment] 2018-06-12 10:50
May be server side check for referer and origin match.
