### ISSUE TITLE
[Question] Rule to Disable WebRTC

### ISSUE THREAD

**Issue by rebekah65** [uBlockOrigin/uMatrix-issues#71] opened 2018-10-09 10:41 UTC
Is there anyway i can currently disable WebRTC using a rule.
Thanks

**Comment by gorhill** [comment] 2018-10-09 11:04
Duplicate of <https://github.com/gorhill/uBlock/issues/3225>.

Respect the template please, it expressly asked to first search for duplicates.

**Closed by gorhill** 2018-10-09 11:04 UTC
Labels: duplicate, invalid
