### ISSUE TITLE
Service Worker XHR Requests not shown in Dashboard

### ISSUE THREAD

**Issue by SuperSandro2000** [uBlockOrigin/uMatrix-issues#242] opened 2020-04-05 07:55 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When loading a Gitea instance after the service worker got installed, xhr requests are not shown in the dashboard.

### A specific URL where the issue occurs

https://gitea.com/golang/go

### Steps to Reproduce

1. Load page once
2. Reload with F5
3. open dashboard and there are no xhr requests for ``secure.gravatar.com``

### Ruleset

![image](https://user-images.githubusercontent.com/7258858/78469538-785a5200-7722-11ea-9a71-1e5c991adc93.png)

### Supporting evidence

![image](https://user-images.githubusercontent.com/7258858/78469545-86a86e00-7722-11ea-90eb-e68ed995a06b.png)

![image](https://user-images.githubusercontent.com/7258858/78469552-91fb9980-7722-11ea-9b02-5742fa0547a4.png)

If you block XHR for ``secure.gravatar.com`` and reload the page with F5 you are missing avatars (see below) but the dashboard does not report that despite it being logged (seen in the logger screenshot above).

![image](https://user-images.githubusercontent.com/7258858/78469568-be171a80-7722-11ea-9dee-5ead19c9626e.png)

Also the following gets logged and you have no idea why and think your CSP is broken for 3 hours.

![image](https://user-images.githubusercontent.com/7258858/78469594-f9b1e480-7722-11ea-8ebf-ac1acd2f9278.png)

![image](https://user-images.githubusercontent.com/7258858/78469599-0df5e180-7723-11ea-870e-271d2b6bdb8d.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Chrome 80.0.3987.149
* Operating System and version: Windows 10 Pro 1909 18363.752

**Comment by uBlock-user** [comment] 2020-04-05 08:05
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/239

Tabless requests will never appear in the popup UI panel of uMatrix/uBO.

**Closed by uBlock-user** 2020-04-05 08:05 UTC

**Comment by SuperSandro2000** [comment] 2020-04-05 08:16
> Tabless requests will never appear in the popup UI panel of uMatrix/uBO.

Why will they not appear? In this scenario the service worker will only work when it intercepts a request from the current tab and to hide that makes no sense.

**Comment by gorhill** [comment] 2020-04-05 12:19
See <https://github.com/uBlockOrigin/uMatrix-issues/issues/92#issuecomment-457866811>.
