### ISSUE TITLE
sub domains not grouped/associated to TLD

### ISSUE THREAD

**Issue by paponius** [uBlockOrigin/uMatrix-issues#29] opened 2018-07-12 08:16 UTC
### Prerequisites

completed all steps, behavior remains in a new profile/single extension
but note that I only use uMatrix for couple of days

### Description

Unexpected behavior on www.myqnapcloud.com
- sub-domains of the visited domain are not grouped
- rules of 1st-party are not applied to sub-domains
- visited domain is not visible in UI
- can't select .com scope (no needed, but it seems weird)

### A specific URL where the issue occurs

https://www.myqnapcloud.com

### Steps to Reproduce

add: `myqnapcloud.com 1st-party script allow`
scripts on static.myqnapcloud.com are not allowed

### Supporting evidence
rule:
`myqnapcloud.com 1st-party script allow`

![screenshot 37](https://user-images.githubusercontent.com/14345371/42620202-986e4318-85ba-11e8-9781-afac431a588b.png)

when **static** sub-domain explicitly allowed:
rules:
`myqnapcloud.com 1st-party script allow`
`myqnapcloud.com static.myqnapcloud.com script allow`

![screenshot 39](https://user-images.githubusercontent.com/14345371/42620503-658d9ccc-85bb-11e8-9839-07da303d5e03.png)

### Your environment

* uMatrix version: uMatrix 1.3.10
* Browser Name and version: Firefox 61.0.1 (64-bit)
* Operating System and version: Windows 10 Pro 1803 b17134.137

**Comment by uBlock-user** [comment] 2018-07-12 08:40
> completed all steps, behavior remains in a new profile/single extension

So why did you remove it ? You're expected to tick all you did instead of removing it.

**Comment by uBlock-user** [comment] 2018-07-12 08:41
I'm seeing the same behaviour in uBO too.

**Comment by gwarser** [comment] 2018-07-12 08:53
First party domain

// QNAP System Inc : https://www.qnap.com
// Submitted by Nick Chang <nickchang@qnap.com>
dev-myqnapcloud.com
alpha-myqnapcloud.com
myqnapcloud.com

**Comment by uBlock-user** [comment] 2018-07-12 09:02
`static.myqnapcloud.com` and `support.myqnapclloud.com` are missing from [PSL](https://publicsuffix.org/list/public_suffix_list.dat), makes sense why both extensions not listing them together with the TLD.

**Comment by gwarser** [comment] 2018-07-12 09:05
You cannot whitelist top level domain (`.com` for example). Its the same with `githubusercontent.com` or `cloudfront.net`

**Comment by uBlock-user** [comment] 2018-07-12 09:07
But you can select `.com` scope, that is possible.

**Comment by gwarser** [comment] 2018-07-12 09:38
Most of this is by design. Tons of duplicate issues. One problem I possibly see is why manually written rule is not propagating to subdomains - but maybe I just don't understand this.

**Comment by gwarser** [comment] 2018-07-12 09:53
`myqnapcloud.com * script allow` is working, this means `static.myqnapcloud.com` is not considered 1st-party to `myqnapcloud.com`

**Comment by gwarser** [comment] 2018-07-12 10:00
This may explain why it's not considered first party

>cloudfront.net is a Public Suffix, meaning x.coudfront.net is not under the same administrative authority as y.cloudfront.net, the same way x.co.uk is not under the same administrative authority as y.co.uk.

>The matrix won't encourage people working below effective domain names. But you can manually enter * cloudfront.net * allow in the "My rules" tab if you want to blanket-allow cloudfront.net.

https://github.com/gorhill/uMatrix/issues/54#issuecomment-62480877

**Comment by uBlock-user** [comment] 2018-07-12 10:06
Not be able to set scope on `raw.githubusercontent.com` is not by-design, though. I'm able to set scope to com on google.com, so I should be able to do that on any other domain too.

**Comment by gwarser** [comment] 2018-07-12 10:16
No. `githubusercontent.com` is TLD and gorhill stated this is not allowed by UI. You can set scope to `githubusercontent.com` on `raw.githubusercontent.com` the same as `com` for `google.com`

>Though the matrix UI does enforce effective domain boundary, you can manually create rules...

https://github.com/gorhill/uMatrix/wiki/Changes-from-HTTP-Switchboard#no-more-restriction-on-effective-domain-boundaries

**Comment by gwarser** [comment] 2018-07-12 10:24
@paponius please explain this point:

- visited domain is not visible in UI

**Comment by uBlock-user** [comment] 2018-07-12 10:39
@gwarser So being able to set scope to `com` or any other TLD for that matter is dictated by PSL ?

**Comment by gwarser** [comment] 2018-07-12 11:00
I this tricky question? :) Yes. This is sort of security measure to prevent allowing too much.

**Comment by gorhill** [comment] 2018-07-12 11:14
> I'm able to set scope to `com` on `google.com`

When I wrote the new scope selector code, I just decided to not restrict in that case.

**Comment by gorhill** [comment] 2018-07-12 11:17
Duplicate of <https://github.com/gorhill/uMatrix/issues/54>.

**Closed by gorhill** 2018-07-12 11:17 UTC
Labels: bug

**Comment by gorhill** [comment] 2018-07-12 11:22
> But you can select `.com` scope, that is possible. Seems you can't set scope to `com` on this domain and the aformentioned ones either

Because most of the time `com` is the effective TLD (as per PSL). In the current case the eTLD is `myqnapcloud.com`. I did allow to go below base domain in the scope selector, but I do not allow to go below the eTLD. For example, you can't go below `co.uk` either.

**Comment by gwarser** [comment] 2018-07-12 22:16
> But this is probably more confusing:
> While adding this rule directly to config:
> myqnapcloud.com myqnapcloud.com script allow
> it does propagate to sub domains, listing script column light-green in UI next to them.
> But whatever scope you select in UI, there is no dark green box representing where from this whitelist originated.
> The line showing myqnapcloud.com is hidden as it's considered a quasi TLD.

This rule can be set from panel by visiting `myqnapcloud.com`, then is reproducible on `www.myqnapcloud.com`, @gorhill ?

**Comment by gorhill** [comment] 2018-07-12 23:19
> This rule can be set from panel by visiting `myqnapcloud.com`

I don't want to second guess the content of the PSL, this would just end up being a huge burden, and introduce arbitrariness -- as said PSL dictates all.

In the end, if whoever is behind the public suffix `myqnapcloud.com` is not respecting their own PSL entry when they serve web pages, I rather have this sort of issues taken to them, it should not be the job of uMatrix to fix the PSL or someone's server. The proper behavior is for the server to redirect request from `myqnapcloud.com` to `www.myqnapcloud.com`.

> But whatever scope you select in UI, there is no dark green box representing where from this whitelist originated.

Dark colors are to represent explicit rules for a specific hostname/type. You do not see a dark green cell for the same reason a rule such as `example.com example.com script allow` won't cause the cell corresponding to `example.com www.example.com script` to be dark green, because the cell itself inherit from a broader rule. If someone manually set such rule in the "My rules" pane, then the assumption is that they understand the behavior of that rule.
