### ISSUE TITLE
Some third party connections listed in Behind the scene instead of site's popup panel

### ISSUE THREAD

**Issue by alexgsgit** [uBlockOrigin/uMatrix-issues#151] opened 2019-05-13 19:54 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

The popup panel doesn't seem to list all 3rd party connections the site is attempting. Instead they are showing up in the logger in the Behind the scene section. For the site I noticed this on these are getting blocked (correctly, as I am in 3rd party default deny) and this is breaking the page. But since they do not show up in the popup panel it is not easy to allow these connections and unbreak the page.

When I allow one of these connections from the Behind the scene tab in the logger the site is fixed and the corresponding rule shows up in "My rules". However, the new rule in My rules looks just like a normal rule for the site (i.e. not some kind of "behind-the-scene rule"), which is why I think this is not expected behavior (or if it is it's at least inconvenient behavior).

### A specific URL where the issue occurs

https://www.tensorflow.org/alpha

### Steps to Reproduce

1. Go to https://www.tensorflow.org/alpha. The display of the menus is messed up (because some xhr's from fonts.gstatic.com are being blocked). Popup panel shows an entry for gstatic.com and www.gstatic.com but not fonts.gstatic.com
2. Go to logger and Behind the scene and reload page. The logger now shows that a bunch of xhr's from fonts.gstatic.com that are blocked
3. In logger click on one of these and allow XHR from fonts.google.com in tensorflow.org scope
4. Now page loads correctly and in My rules is a new rule:
`tensorflow.org fonts.gstatic.com xhr allow`

### Ruleset

```
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: localhost true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: wyciwyg-scheme true
no-workers: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * cookie block
* * frame block
* * script block
* * xhr block
* 1st-party * allow
* 1st-party frame allow
* 1st-party script allow
* 1st-party xhr allow
* google.com * block
```

### Supporting evidence

Weirdly formatted text on menus instead of little triangle images (fonts.gstatic.com not shown in the popup panel):
![image](https://user-images.githubusercontent.com/9270729/57649259-a4775c80-75bf-11e9-879c-80e57ac70caf.png)

In the logger there is nothing going on for the tab in question but a bunch of stuff being blocked in Behind the scene:
![image](https://user-images.githubusercontent.com/9270729/57649397-0768f380-75c0-11e9-8ad1-cc0548676f5b.png)
![image](https://user-images.githubusercontent.com/9270729/57649444-26678580-75c0-11e9-918d-f3830ef42c1d.png)

Picking one of the fonts.gstatic XHR entries and allowing:
![image](https://user-images.githubusercontent.com/9270729/57649533-69295d80-75c0-11e9-8195-9755cf96859f.png)

Now site displays correctly (fonts.gstatic.com still not in popup panel):
![image](https://user-images.githubusercontent.com/9270729/57649583-8eb66700-75c0-11e9-97f6-07e25ea4c38c.png)

New temporary rule added:
![image](https://user-images.githubusercontent.com/9270729/57649649-b5749d80-75c0-11e9-9714-8de48e17e1af.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Vivaldi 2.5.1525.40 (Stable channel) (64-bit)
* Operating System and version: MacOS 10.14.4

**Comment by gorhill** [comment] 2019-05-13 20:07
Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/92#issuecomment-457866811>.

**Closed by gorhill** 2019-05-13 20:07 UTC
Labels: duplicate
