### ISSUE TITLE
Backup Exports format

### ISSUE THREAD

**Issue by crazyyzarc** [uBlockOrigin/uMatrix-issues#265] opened 2020-06-03 05:33 UTC
Do you want to implement backup exports in a format like uBlock? Because I am creating backups every months and this would greatly simplify the distinction.

Current file export: 
my-umatrix-rules.txt
my-umatrix-backup.txt

uBlock file export
my-ublock-backup_**2020-06-03_07.24.09**.txt
my-ublock-custom-filters_**2020-06-03_07.24.02**.txt

Thanks for your commitment

**Comment by uBlock-user** [comment] 2020-06-03 05:49
Duplicate of gorhill/uMatrix#531

**Closed by uBlock-user** 2020-06-03 05:49 UTC
