### ISSUE TITLE
Limited width hides information

### ISSUE THREAD

**Issue by kiwidude** [uBlockOrigin/uMatrix-issues#170] opened 2019-06-29 00:01 UTC
### Prerequisites

- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

Limited width of the uMatrix window hides information and makes it difficult to use:
* Right part of the URL cut off, hiding applicable domain.
* Scroll bar obscuring the right edge of the table. I've seen this hiding more than a single column.
### Steps to Reproduce
Browse to URL shown in screenshot.
Screen size is 1920x1080.
### Your environment

* uMatrix version: see screenshots
* Browser Name and version: FF 60.7.2esr (64-bit)
* Operating System and version: openSUSE 15.0 with current updates

**Comment by kiwidude** [comment] 2019-06-29 00:03
![umatrix-url-cut-off](https://user-images.githubusercontent.com/1336061/60376892-c6407c00-9a65-11e9-81aa-eb3cbef17443.png)
![umatrix-scrollbar-width](https://user-images.githubusercontent.com/1336061/60376894-cc365d00-9a65-11e9-9b4c-ccc3398cd5b0.png)

**Comment by uBlock-user** [comment] 2019-06-29 05:41
Duplicate of https://github.com/gorhill/uMatrix/issues/811

**Closed by uBlock-user** 2019-06-29 05:41 UTC
