### ISSUE TITLE
Feature Request: synchronization locally

### ISSUE THREAD

**Issue by Golutazem** [uBlockOrigin/uMatrix-issues#193] opened 2019-10-25 10:40 UTC
uMatrix and uBlock can synchronize over a cloud service, but not locally.
This request is to implement a feature to synchronize between different browsers or different browser profiles on the same computer.

**Comment by uBlock-user** [comment] 2019-10-25 12:27
Duplicate of https://github.com/gorhill/uMatrix/issues/433

**Closed by uBlock-user** 2019-10-25 12:27 UTC
