### ISSUE TITLE
Blocked XHRs for some 3rd party domains not represented in matrix view on Chromium & Iridium

### ISSUE THREAD

**Issue by nothingmuch** [uBlockOrigin/uMatrix-issues#280] opened 2020-07-21 23:50 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix extension is wholly disabled or not installed
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset -- i'm not sure what "the logger" refers to, I am only familiar with the web developer console which I did use, but if uMatrix has its own logger than I didn't do this

### A specific URL where the issue occurs

https://twitter.com/explore (as redirected by the home page when not logged in)

### Steps to Reproduce

1. Open twitter.com, observe failure to load but lack of blocked XHR request indicator under `abs.twimg.com` row
2. apply additional rule permitting XHRs to `abs.twimg.com`, reload, observe successful loading but lack of allowed XHR request indicator under `abs.twimg.com`

### Ruleset

```https-strict: behind-the-scene false
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: moz-extension-scheme true
matrix-off: opera-scheme true
matrix-off: vivaldi-scheme true
matrix-off: wyciwyg-scheme true
noscript-spoof: * true
referrer-spoof: * true
referrer-spoof: behind-the-scene false
* * * block
* * css allow
* * frame block
* * image allow
* 1st-party cookie allow
* 1st-party frame allow
* 1st-party media allow
twitter.com * script allow
twitter.com 1st-party xhr allow
twitter.com giphy.com xhr allow
twitter.com pbs.twimg.com xhr allow
twitter.com riffsy.com xhr allow
twitter.com video.twimg.com media allow
twitter.com video.twimg.com xhr allow
```

Upon adding the rule:

```
twitter.com abs.twimg.com xhr allow
```
or
```
twitter.com * xhr allow
```
(the latter is what is in the screenshot below, but I've confirmed both work)

the website loads, but the request counts in the matrix appear the same

### Supporting evidence

Note the absence of a number in the `abs.twimg.com` x XHR cell in both screenshots.

![image](https://user-images.githubusercontent.com/14242/88117303-4c1bf180-cbaa-11ea-822d-069ff7e74978.png)
![image](https://user-images.githubusercontent.com/14242/88117406-8e453300-cbaa-11ea-96e5-57b62672a362.png)

The actual resource that appears to fail to load is a script on `abs.twimg.com`, fetched in an XHR (I believe as part of webpack loading, but not sure as I've no experience with that):

![image](https://user-images.githubusercontent.com/14242/88117688-4bd02600-cbab-11ea-9a64-8700ba02fd1a.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Iridium 2020.04
* Operating System and version: Fedora 32 appvm on Qubes 4

**Comment by nothingmuch** [comment] 2020-07-21 23:58
Also seems to happen on `Chromium 83.0.4103.116 Fedora Project` (also w/ 1.4.0):

![image](https://user-images.githubusercontent.com/14242/88118741-ecbfe080-cbad-11ea-9dd1-0fa18c8b54ca.png)
![image](https://user-images.githubusercontent.com/14242/88118773-02cda100-cbae-11ea-8771-173d49db020d.png)

**Comment by ghost** [comment] 2020-07-22 06:37
Use the logger

![image](https://user-images.githubusercontent.com/886325/88142674-3502f100-cbf6-11ea-8635-379e2fa21a0b.png)

These are tab-less requests from service worker.

Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/92#issuecomment-457866811

**Closed as completed by ghost** 2020-07-22 06:37 UTC
Labels: duplicate
