### ISSUE TITLE
Cookies are not blocked

### ISSUE THREAD

**Issue by I-O-1** [uBlockOrigin/uMatrix-issues#137] opened 2019-04-21 20:30 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Steps to Reproduce

1. Open [http://raymondhill.net/httpsb/httpsb-test-cookie-1.php](url)
2. Block cookies using uMatrix menu
3. Refresh page

### Ruleset

Defaults after installation.

### Supporting evidence

![uMatrix 1](https://user-images.githubusercontent.com/20108633/56475169-5aea9480-648d-11e9-94b6-e82981ea702c.png)
![uMatrix 2](https://user-images.githubusercontent.com/20108633/56475170-5aea9480-648d-11e9-94ae-a912e4885b54.png)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Chrome 73.0.3683.103
* Operating System and version: Windows 10 Pro 1809 (17763.379)

**Comment by uBlock-user** [comment] 2019-04-21 20:46
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/74

Fixed in https://github.com/gorhill/uMatrix/releases/tag/1.3.17b1, install the dev build or wait for stable release.

**Closed by uBlock-user** 2019-04-21 20:46 UTC
