### ISSUE TITLE
Phys.org something weird is causing Firefox to use 100% cpu despite blocking all scripts, webworkers

### ISSUE THREAD

**Issue by neuroelectronic** [uBlockOrigin/uMatrix-issues#114] opened 2019-02-19 23:15 UTC
### Prerequisites

Using Umatrix on Phys.org, any page on the domain causes this issue.
Firefox 65.0.1 (64-bit)

Windows 10 Home 1803

### Description

Some script on Phys.org is able to ignore the uMatrix filtering rules and causes the browser to use 100% cpu usage, and memory usage to balloon to all available memory on my machine.  This causes the browser to become unresponsive.  The uMatrix icon shows a count of >1 despite only having 1 or 0 domains white listed.   I'm not sure exactly what this count signifies so it may or may not be a symptom of the problem. Specifically, i'm seeing the number 13 when having just phys.org whitelisted. 

This issue effecting many users.  see: https://old.reddit.com/r/uMatrix/comments/arjes3/how_is_malware_from_the_physorg_able_to_run/

### A specific URL where the issue occurs

https://phys.org 

or any article page

### Steps to Reproduce

1. Go to Phys.org home page
2. watch cpu
3. disable any and all scripts on the domain
4. watch cpu

### Ruleset

any and all rules, issue persist despite blocking everything.  see reddit link above for proof (not my reddit post)

### Supporting evidence

see reddit link above for proof (not my reddit post)

### Your environment

* uMatrix version: v1.18.4
* Browser Name and version: Firefox 65.0.1 (64-bit)
* Operating System and version: Windows 10 Home 1803

**Comment by gorhill** [comment] 2019-02-19 23:41
Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/90>.

**Closed by gorhill** 2019-02-19 23:41 UTC
Labels: duplicate

**Comment by neuroelectronic** [comment] 2019-02-20 01:50
@gorhill, sorry didn't see the original issue because it was closed.
