### ISSUE TITLE
Corrupted Content error when using uMatrix with Firefox on discourse forum websites

### ISSUE THREAD

**Issue by sloxy** [uBlockOrigin/uMatrix-issues#79] opened 2018-10-27 10:48 UTC
### Prerequisites

- [ Y] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [Y ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [Y ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [Y ] uMatrix is the only extension
    - [Y ] uMatrix with default lists/settings
    - [ Y] using a new, unmodified browser profile
- [Y ] I am running the latest version of uMatrix
- [Y ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [Y ] I used the logger to rule out that the issue is caused by my ruleset

### Description

When uMatrix is installed & enabled, Firefox starts having "Corrupted Content" error when visiting site.
When uMatrix is not installed, this does not happen.
When uMatrix is installed but the global (\*) is not enabled, this does not happen.
When uMatrix is installed, the global (\*) is enabled, but site rule is not enabled, this **does** happen.

### A specific URL where the issue occurs
clojureverse.org

### Steps to Reproduce

1. Open Firefox, Install uMatrix
2. Visit clojureverse.org
3. See error

### Supporting evidence

youtube video of new profile in firefox without issue occurring, then umatrix installed & error occurs: https://youtu.be/1ap_Fx3IK_8

discussion on Discourse forum where other sites and users are experiencing it along with some other thoughts from users: https://meta.discourse.org/t/firefox-experiences-network-protocol-violation-on-discourse-based-websites/97308

screenshot of error: 
![f6f7dd6f7b84a69b8bbf3f59070500834352aa68_1_1035x582](https://user-images.githubusercontent.com/36491088/47603024-26b28180-d9de-11e8-9779-0db9d430ffc9.png)

also opened bug against Firefox : https://bugzilla.mozilla.org/show_bug.cgi?id=1502606 as this issue does not occur in Chrome on Windows with uMatrix

### Your environment

* uMatrix version: 1.3.14
* Browser Name and version: 63.0
* Operating System and version: Windows 10, version 1803

**Comment by sloxy** [comment] 2018-10-27 10:59
some other affected sites which I could reproduce against are: 
https://elixirforum.com
https://meta.discourse.org/
https://community.freepbx.org/

**Comment by gorhill** [comment] 2018-10-27 11:05
> [ Y] I performed a cursory search of the issue tracker to avoid opening a duplicate issue 

Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/72>.

**Closed by gorhill** 2018-10-27 11:05 UTC
Labels: duplicate

**Comment by sloxy** [comment] 2018-10-27 11:12
apologies. i had looked through the open issues and couldn't see it (i can see it's now closed and in RC for next version) 

👍
