### ISSUE TITLE
All rules disappear / reset to default rules, probably when quit Firefox

### ISSUE THREAD

**Issue by BillDietrich** [uBlockOrigin/uMatrix-issues#129] opened 2019-04-11 07:53 UTC
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

My entire permanent rule-set gets deleted / reset to default rules quite often, I think when I quit Firefox or launch Firefox.

### Steps to Reproduce

It's intermittent, so I've been unable to nail down any more precise situation.  I'll work all day, building up rules, saving to permanent, then quit for the day, shut down the computer.  Start it up next morning, open Firefox, all rules are gone (back to default rules).

### Supporting evidence

Would just be a screenshot of the default rules.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version:  Firefox 66.0.2
* Operating System and version: Linux Mint 19.1

But this has been happening for a while, I think (it's intermittent).  Happened on previous versions of Firefox, and I think on Linux Mint 19 too.

I suspect it's something to do with storage size of the DB in Firefox, or clearing storage ?  In Firefox preferences, under Cookies and Site Data, it says "Your stored cookies, site data and cache are currently using 1.0 GB of disk space."  I have "Delete cookies and site data when Firefox is closed" turned off.

Does uMatrix have a limit on the size of the ruleset ?  What happens if uMatrix hits the limit for data storage in Firefox ?  My exported rules file has about 2900 lines in it.

**Comment by uBlock-user** [comment] 2019-04-11 08:02
> - I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile

You didn't try to reproduce in those following conditions, try those first.

**Comment by gwarser** [comment] 2019-04-11 08:47
https://old.reddit.com/r/uMatrix/comments/b6hndd/rules_disappearing/

**Comment by uBlock-user** [comment] 2019-04-11 08:57
Ccleaner is not responsible, I use that myself for years now, this sounds like a Firefox storage issue

**Comment by BillDietrich** [comment] 2019-04-11 09:11
To clarify a few points:

- I don't use CCLeaner.  I use Bleachbit every couple of months, but haven't used it in a month or more now, and all my rules just disappeared again when I shut down overnight and started again this morning.  So no correlation with Bleachbit use.

- I don't use private browsing in Firefox.  I do have Facebook Container enabled, and Privacy Badger and some other add-ons.

- I used to have Firefox set to clear cookies when it closed, but I got rid of that setting a while ago, thought it might be affecting uMatrix.

**Comment by uBlock-user** [comment] 2019-04-11 09:16
@BillDietrich Try to reproduce in a new profile

**Comment by BillDietrich** [comment] 2019-04-11 09:54
I have created a new FF profile, added only uMatrix, imported my rules from backup.  Can't reproduce the problem just by closing and launching Firefox repeatedly.  But same is true of my normal profile, loaded up with other add-ons etc.  As I said, the problem seems intermittent.  I'll keep trying with the new mostly-empty profile.

**Comment by gorhill** [comment] 2019-04-11 12:24
>  What happens if uMatrix hits the limit for data storage in Firefox ?

As far as I know, the storage limit is not enforced yet on Firefox.

> sounds like a Firefox storage issue OP here must be using private browsing mode or history is set to never remember

Can't be, rules are saved as user settings, and user settings are always saved in webext storage, which is not affected by the config entries affecting IndexedDB.

**Comment by BillDietrich** [comment] 2019-04-12 07:49
Okay, some more information that points in a different direction:

This morning, booted up my system, logged in, launched Firefox with the new mostly-empty profile with just uMatrix, and all of my rules were gone.  Quit Firefox, launched it again with my default profile full of add-ons etc, and wasn't sure, maybe some rules were missing.  Quit Firefox, launched into the new mostly-empty profile again, and all of my rules were there, not missing !

So now I'm wondering if this is some system-startup-time or system-load issue.  After I log in, I'm launching several applications mostly-simultaneously, some system services are starting, and I have the system set to FSCK /home (paranoid because months ago I had lots of OS GUI freezes that required hard power-down).  So maybe, launching Firefox while the system is under heavy load results in my uMatrix rules not being read ?

Does uMatrix have any timeout on reading the rule database ?  Suppose it doesn't get a response within 5 or 10 seconds.  Would it give up and revert to the default rule-set ?

**Comment by gorhill** [comment] 2019-04-12 10:39
> Does uMatrix have any timeout on reading the rule database ?

No. uMatrix plainly uses the webext API which is just a key-value store, and it knows nothing about file system.

**Comment by Lyberta** [comment] 2019-04-12 17:33
Hitting the same issue.

OS: Debian Testing amd64
Firefox version: 60.6.1esr (64-bit)

I can see my rules in `browser-extension-data/uMatrix@raymondhill.net/storage.js` yet when I start Firefox, the rules are not in the GUI.

**Comment by gorhill** [comment] 2019-04-12 19:29
> the rules are not in the GUI

Was the dashboard already opened in a tab? If so, close it and re-open and see if the rules are there.

**Comment by Lyberta** [comment] 2019-04-12 19:34
> Was the dashboard already opened in a tab? If so, close it and re-open and see if the rules are there.

No, it doesn't work. I have also tried deleting `storage.js` and importing rules again from a txt file. When I close Firefox, I see rules properly imported into `storage.js` but when I open it again and open dashboard tab, the rules are default.

**Comment by Lyberta** [comment] 2019-04-12 22:49
Seems to be an indexedDB corruption. I deleted `storage/default/moz-extension+++95519255-adbf-41c8-bee1-4f68be8ad0b7` and got my rules back.

**Closed** 2019-05-19 16:44 UTC
Labels: Firefox, external, unable to reproduce
