### ISSUE TITLE
When blocking a website, tell me why

### ISSUE THREAD

**Issue by JeffCarpenter** [uBlockOrigin/uMatrix-issues#202] opened 2019-11-10 07:21 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- Feature request
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

When uMatrix blocks a website and it redirects me to main-blocked.html, I'd like to know why. That is, I want to see what what rule and ruleset is being enforced (so I can report false positives and that sort of thing). Ideally this message would show up on main-blocked.html itself. 

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 70.0.1 (64-bit)
* Operating System and version: Manjaro Linux Testing

**Comment by uBlock-user** [comment] 2019-11-10 07:56
Duplicate of https://github.com/gorhill/uMatrix/issues/526

**Closed by uBlock-user** 2019-11-10 07:56 UTC

**Comment by JeffCarpenter** [comment] 2019-11-10 22:46
I did search but didn't see that issue. Sorry guys!
