### ISSUE TITLE
Firefox keyboard shortcuts

### ISSUE THREAD

**Issue by masaeedu** [uBlockOrigin/uMatrix-issues#37] opened 2018-07-26 15:40 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - There's a couple of locked issues on the original issue tracker about this but AFAICT there's still no way to use keyboard shortcuts to control uMatrix on Firefox
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - **N/A**
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior: **N/A**

### Description

I would like to be able to adjust uMatrix settings using keyboard shortcuts on Firefox. A good starting point would be the ability to have coarse grained control such as "allow all scripts in current context" or "allow all first party XHR", etc.

Depending on how easy it is to implement, it might also be useful to let the user use the keyboard to go through domains that were blocked (but that are not blacklisted), and use one of two keys to decide whether to whitelist it globally or whitelist it in the current context.

### Your environment

* uMatrix version: 1.3.12
* Browser Name and version: Firefox 61.0.1
* Operating System and version: Arch Linux (version N/A)

**Comment by gwarser** [comment] 2018-07-26 15:59
You will have these:

![image](https://user-images.githubusercontent.com/886325/43273756-919b4b14-90fd-11e8-8a7b-8adc69730cc8.png)


as soon as this bug will be implemented https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by gwarser** [comment] 2018-07-26 16:06
Actually, these shortcuts are missing from Chrome too - https://github.com/gorhill/uMatrix/issues/678

**Comment by masaeedu** [comment] 2019-03-01 00:58
It looks like Firefox [has added support](https://www.bleepingcomputer.com/news/software/firefox-66-lets-you-reconfigure-keyboard-shortcuts-for-extensions/) for addon shortcuts in the latest 66.0 release. However, there don't seem to be any shortcuts visible for uMatrix in the shortcut configuration page

![image](https://user-images.githubusercontent.com/3674056/53609090-44ae0f80-3b93-11e9-958e-05f1140dc7fb.png)

**Comment by notJerl** [comment] 2019-10-24 20:55
uMatrix for Firefox still has no keyboard shortcuts available.  Even worse, if you manage to navigate to the popup (Ctrl+L to get to navbar, tab twice to get to add-on icons, arrow keys to select uMatrix icon and space/enter to open it), there's no way to actually navigate within the popup using the keyboard.  This is forcing me to use MouseKeys to change uMatrix settings, which is, well, sub-optimal.

**Comment by mhussaincov** [comment] 2019-10-28 11:35
hi there,
could keybord shortcuts be added?
or could the interface be made more accessible?
visually impared screen reader user here,
it would help a great deel if this could be added?

Majid

On 24/10/2019, notJerl <notifications@github.com> wrote:
> uMatrix for Firefox still has no keyboard shortcuts available.  Even worse,
> if you manage to navigate to the popup (Ctrl+L to get to navbar, tab twice
> to get to add-on icons, arrow keys to select uMatrix icon and space/enter to
> open it), there's no way to actually navigate within the popup using the
> keyboard.  This is forcing me to use MouseKeys to change uMatrix settings,
> which is, well, sub-optimal.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/uBlockOrigin/uMatrix-issues/issues/37#issuecomment-546099520


-- 
kind regards,
Majid Hussain

**Comment by 5hir0kur0** [comment] 2019-11-08 09:27
Hi!
Is anyone already working on this?
If not, I'd like to try getting this to work.

**Comment by girst** [comment] 2019-11-10 15:02
@5hir0kur0 -- go for it!

**Comment by 5hir0kur0** [comment] 2019-11-11 17:09
So, I've made some progress.
I tried to re-implement the commands that were removed in [this commit](https://github.com/gorhill/uMatrix/commit/f2d7d32d1e5191630fdb2bb769c63eb5fbd80529).
(`"whitelist-page-domain"` was in `manifest.json` but not implemented in `commands.js` so I didn't implement it.)

I've made `whitelist-all` and `revert-all` automatically reload the tab, which the versions that were removed didn't do. I'll remove this feature if you don't like it.

I've added a keyboard shortcut that activates the popup (Alt+P).
This would mainly be useful in conjunction with what @girst implemented for issue #197.

I've also noticed an issue with the `whitelist-all` command: If the default scope is set to something more general than `site` (i.e. global/`*` or `domain`) it _does_ whitelist the resources for the current hostname, but they still show up in the matrix as red (unless you change the scope in the popup to the site scope). E.g. the JavaScript is executed but it shows the corresponding cells as red. I'm not sure if that is the intended behavior.

An alternative implementation that I have tried is to simulate what the "power" button does, i.e. disable uMatrix for the default scope:
```javascript
// Toggle uMatrix on and off in the current tab (at the default scope level).
// Similar to pressing the power button in the popup.
const toggleInDefaultScope = async function() {
    const switchName = 'matrix-off';
    const currentId = await getCurrentTabId();
    const pageStore = µm.pageStoreFromTabId(currentId);
    let scope = '*';
    if (µm.userSettings.popupScopeLevel === 'domain') {
        scope = pageStore.pageDomain;
    } else if (µm.userSettings.popupScopeLevel === 'site') {
        scope = pageStore.pageHostname;
    }
    µm.tMatrix.setSwitchZ(
        switchName,
        scope,
        µm.tMatrix.evaluateSwitchZ(switchName, scope) === false
    );
    µm.forceReload(currentId);
}
```
If it's implemented like this, at least the effect of pressing the shortcut is always visible in the popup. This, however, has the obvious disadvantage of disabling uMatrix in the global scope if the default scope is set to global.

You can take a look at my changes [here](https://github.com/5hir0kur0/uMatrix/commit/b179512ba83ba8afc4599dc6b5609d2d241d8408). I've tested it with Chrome and Firefox and it seems to work (except for the strange behavior mentioned above).

**Comment by masaeedu** [comment] 2019-11-11 17:25
Sweet, can't wait to try these out!

**Comment by girst** [comment] 2019-11-11 17:41
On Mon, Nov 11, 2019 at 09:09:08AM -0800, 5hir0kur0 wrote:
>I've made `whitelist-all` and `revert-all` automatically reload the 
>tab, which the versions that were removed didn't do. 

please don't. this is unexpected behaviour, and doesn't really make 
sense. if revert-all is issued, it effects all tabs, not just the 
focused one. (but refreshing all tabs is definetly not a good idea).  
This also break the workflow "allow something, refresh, then immediately 
disable it again to not forget it later".

>An alternative implementation that I have tried is to simulate what the 
>"power" button does, i.e. disable uMatrix for the default scope:

that seems reasonable, although I haven't looked at what whitelist-all 
did before.

**Comment by 5hir0kur0** [comment] 2019-11-11 17:55
> please don't. this is unexpected behaviour, and doesn't really make sense. if revert-all is issued, it effects all tabs, not just the focused one. (but refreshing all tabs is definetly not a good idea). This also break the workflow "allow something, refresh, then immediately disable it again to not forget it later".

I agree, for `revert-all` it's not a good idea. I'll remove it.

What about `whitelist-all`, though? It only whitelists the current tab's hostname.
As far as I can tell, that is what the old version did as well. It called this function
```js
µMatrix.autoWhitelistAllTemporarily = function(pageURL) {
    var srcHostname = this.URI.hostnameFromURI(pageURL);
    if ( this.mustBlock(srcHostname, '*', '*') === false ) {
        return false;
    }
    this.tMatrix.whitelistCell(srcHostname, '*', '*');
    return true;
};
```
on the URL of the tab returned by `vAPI.tabs.get(null, whitelistAll);`.
This function executes a query for the currently active tab if the first parameter is `null`: 
```js
    chrome.tabs.query({ active: true, currentWindow: true }, onTabReceived);
```

**Comment by uBlock-user** [comment] 2019-11-11 17:55
> Is anyone already working on this?

It's an open issue, when it gets worked on, you will a see commit mentioning this issue.

**Comment by gorhill** [comment] 2020-04-20 11:45
Duplicate of <https://github.com/gorhill/uMatrix/issues/678>.

**Closed by gorhill** 2020-04-20 11:45 UTC
Labels: Firefox, enhancement
