### ISSUE TITLE
asset update fails

### ISSUE THREAD

**Issue by reinterpret-cast** [uBlockOrigin/uMatrix-issues#65] opened 2018-09-28 15:24 UTC
### Prerequisites

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uMatrix
- [X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior

### Description

Update of assets seem to have no effect

### Steps to Reproduce

1. Go to settings
2. Update assets + observe download of updated documents e.g. in wireshark
3. Check asset in asset-viewer. it displays the old document

### Supporting evidence

I'm trying to attach screenshots but something is not working :/

### Your environment

* uMatrix version: uMatrix 1.3.14
* Browser Name and version: Firefox 62

* Operating System and version: Windows 7

**Comment by reinterpret-cast** [comment] 2018-09-28 15:29
![wireshark_request](https://user-images.githubusercontent.com/43678985/46218053-33867b80-c333-11e8-9cae-a940eb2343d9.jpg)
![asset_viewer](https://user-images.githubusercontent.com/43678985/46218060-384b2f80-c333-11e8-91c9-c30fb2561128.jpg)

Where is/should the asset be stored in the file system?

**Comment by gwarser** [comment] 2018-09-28 15:54
Private browsing? "Firefox will "Never remember history"?

**Comment by reinterpret-cast** [comment] 2018-09-29 07:38
yes

**Comment by gorhill** [comment] 2018-09-29 09:33
Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/11>.

https://bugzilla.mozilla.org/show_bug.cgi?id=1313401

**Closed by gorhill** 2018-09-29 09:33 UTC
Labels: Firefox, duplicate
