### ISSUE TITLE
uMatrix slows down website

### ISSUE THREAD

**Issue by curiosity-seeker** [uBlockOrigin/uMatrix-issues#150] opened 2019-05-13 12:19 UTC
### Prerequisites

- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x ] uMatrix is the only extension
    - [x ] uMatrix with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uMatrix
- [x ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x ] I used the logger to rule out that the issue is caused by my ruleset

### Description

With uMatrix in FF loading and navigating specific websites is considerably slower than with uBO.

### A specific URL where the issue occurs

www.spiegel.de

### Steps to Reproduce

1. Create new profile for FF 66.0.5 and keep default settings.
2. Install uBO with default settings and load www.spiegel.de : The website loads very fast.
3. Install uMatrix with default settings and reload www.spiegel.de : A performance degradation might not be observable immediately but after restarting FF. Loading sites and navigating in that domain is considerably slower compared to uBO alone.
4. Deactivate uMatrix for that site makes it load fast again. 
5. Countercheck: Activate uMatrix for that site again and deactivate uBO. The site is slower again.

### Ruleset

Default ruleset and settings. However, the slowdown is also observable with a modified ruleset in my regular FF profile.

### Supporting evidence
![Logger1](https://user-images.githubusercontent.com/14075215/57620573-737c3500-7589-11e9-8df9-a807a615a5de.png)
![Logger2](https://user-images.githubusercontent.com/14075215/57620574-7414cb80-7589-11e9-815d-07b2d9ded070.png)
![Logger3](https://user-images.githubusercontent.com/14075215/57620575-7414cb80-7589-11e9-9276-bd009784612e.png)
![Logger4](https://user-images.githubusercontent.com/14075215/57620578-7414cb80-7589-11e9-892f-db63bb349c29.png)
![Logger5](https://user-images.githubusercontent.com/14075215/57620579-74ad6200-7589-11e9-9c8f-857f0acc71da.png)
![Logger6](https://user-images.githubusercontent.com/14075215/57620580-74ad6200-7589-11e9-8998-766c17d6cf79.png)
![Browser-console1](https://user-images.githubusercontent.com/14075215/57620696-d2da4500-7589-11e9-8f74-9528e09a6068.png)
![Browser-console2](https://user-images.githubusercontent.com/14075215/57620697-d2da4500-7589-11e9-9111-c0bfd7087769.png)

### Your environment

* uMatrix version: 1.3.16 (in my regular profile: 1.3.17rc0)
* Browser Name and version: FF 66.0.5
* Operating System and version: Manjaro Linux

**Comment by gorhill** [comment] 2019-05-13 12:28
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data + analysis supporting the claim

Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/93>.

**Closed by gorhill** 2019-05-13 12:28 UTC
Labels: duplicate, invalid
