### ISSUE TITLE
CanvasBlocker prevent to stop scripts in uMatrix

### ISSUE THREAD

**Issue by Zitronella** [uBlockOrigin/uMatrix-issues#183] opened 2019-08-14 00:53 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
uMatrix  load deactivated scripts, when webextension [Canvas Blocker](https://addons.mozilla.org/de/firefox/addon/canvasblocker/) is installed

uMatrix should not load script when it is disabled
### A specific URL where the issue occurs
i assume all URLs but i testet specific on [https://mozhelp.dynvpn.de/dateien/onfocus-onblur/test2.html](https://mozhelp.dynvpn.de/dateien/onfocus-onblur/test2.html) and [https://www.whatismybrowser.com/detect/is-javascript-enabled](https://www.whatismybrowser.com/detect/is-javascript-enabled)

### Steps to Reproduce

1. Fresh Firefox Profile
2. Install uMatrix (let default settings)
3. install Canvas Blocker (let default settings)
4. go to Website i mentioned above
5. deactivate Script in uMatrix for this site and reload
6. also reload with ctr+F5 again
7. see that JS is running
8. deactivate Canvas Blocker
9. refresh Page-> see JS is not runnig anymore

### Supporting evidence
I made a video from this behaviour you can see [here](https://mozhelp.dynvpn.de/dateien/onfocus-onblur/umatrix-canvasblocker.mp4)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 68.0.1 (64bit)
* Operating System and version: Windows 10 Home 64bit

**Comment by Zitronella** [comment] 2019-08-14 01:26
Just found this [https://github.com/kkapsner/CanvasBlocker/issues/263](https://github.com/kkapsner/CanvasBlocker/issues/263) it seems to be a firefox bug, not fixeded yet :(

**Comment by uBlock-user** [comment] 2019-08-14 05:29
Duplicate of https://github.com/uBlockOrigin/uMatrix-issues/issues/149

**Closed by uBlock-user** 2019-08-14 05:29 UTC
