### ISSUE TITLE
Bug in interaction between uMatrix and the Snowflake webextension (torproject)

### ISSUE THREAD

**Issue by opusforlife2** [uBlockOrigin/uMatrix-issues#224] opened 2020-02-20 22:20 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ ] I used the logger to rule out that the issue is caused by my ruleset

### Description

 Error in Snowflake debug console, caused by a line in vapi-background.js in uMatrix:

`Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.`

The uMatrix setting causing this error is:

`Spoof HTTP referrer string of third-party requests`, when set to true.

This is a bug either in Snowflake, or uMatrix. Same issue on the Snowflake bug tracker: https://trac.torproject.org/projects/tor/ticket/33405#ticket

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Have the uMatrix setting enabled.
2. Open the Snowflake debug console in Firefox.
3. The error is visible.

### Ruleset

N/A

### Supporting evidence

![ss1](https://user-images.githubusercontent.com/53176348/74984910-60f32e00-542e-11ea-8116-b57ca115766d.png)

![ss2](https://user-images.githubusercontent.com/53176348/74984957-736d6780-542e-11ea-80ae-f431b32e5b35.png)

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox Beta 74.0b5
* Operating System and version: Windows 7 (64-bit)

**Comment by gorhill** [comment] 2020-02-20 22:23
What is "SnowFlake"?

**Comment by gorhill** [comment] 2020-02-20 22:29
Duplicate of #209.

**Closed by gorhill** 2020-02-20 22:29 UTC
