### ISSUE TITLE
Inline script doesn't get blocked when CSP is set by another extension

### ISSUE THREAD

**Issue by mowgli** [uBlockOrigin/uMatrix-issues#149] opened 2019-05-12 16:15 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [ ] uMatrix is the only extension
    - [ ] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

When I block scripts completly, inline scripts are not blocked.

For example, I have one inline script on my site https://www.ethgen.ch/ displaying this horrible box. When I call that page with js disabled it still gets viewed. (The box in umatrix shows a "1" on a light red box and the log says it was blocked.)

I can block it with the parallel installed ublock but not with umatrix alone.

### A specific URL where the issue occurs

Sample page: https://www.ethgen.ch/ (or http://www.ethgen.ch/ for all not trusting the only marginal trustable CA)

### Steps to Reproduce

1. [First Step]
Disable JS in umatrix
2. [Second Step]
Go to that site above
3. [and so on...]
See that horrible box

### Ruleset

```
https-strict: * true
no-workers: * true
noscript-spoof: * true
referrer-spoof: * true
* * * block
* * cookie block
* * css allow
* * frame block
* * image allow
* * other block
* * script block
* 1st-party * allow
* 1st-party frame allow
```

Thats all matching the site.

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Firefox 66.0.5
* Operating System and version: Linux (unrelated)

**Comment by mowgli** [comment] 2019-05-12 16:15
Here is a screenshot of the log

**Comment by uBlock-user** [comment] 2019-05-12 16:26
![](https://i.gyazo.com/6d7be8ed4fbff37f7b4fc03853bf6a5b.png)

As per the above picture, working as expected.

**Comment by gorhill** [comment] 2019-05-12 16:26
Unable to reproduce.

You did not check these two boxes:

- uMatrix is the only extension
- using a new, unmodified browser profile

Please fulfill and report results of these steps.

**Comment by mowgli** [comment] 2019-05-12 16:40
Yes, I did not checked that settings.

Now I also tested in a plain new browser (hard to fulfil as I have to remove my whole profile directory and the browser is nearly not usable afterwards; no menu, ...)

However, the error only appears in combination with ublock (It is from you too) With umatrix alone it is not reproducable. But I mentioned ublock above too.

**Comment by gorhill** [comment] 2019-05-12 16:49
> With umatrix alone it is not reproducable

Then it's probably because of <https://bugzilla.mozilla.org/show_bug.cgi?id=1462989>.

**Comment by gorhill** [comment] 2019-05-12 16:51
> hard to fulfil as I have to remove my whole profile directory

You can create/use a new profile by visiting `about:profiles`.

**Comment by mowgli** [comment] 2019-05-12 19:50
Do you see any way to work around that bug?

Any way to be sure that on a given site javascript is fully switched of?

Is using noscript an option that is relyable? I seen that bug when I was thinking about reducing addons to have only one addon (umatrix) as autorative for JS and ublock for blocking lists.

**Comment by uBlock-user** [comment] 2019-05-12 20:12
> Do you see any way to work around that bug?

That bug only gets triggered when both uBO and uMatrix are setting up CSPs and Firefox chooses one. That's not the case here if you're not inserting any CSP filter via uBO. Are you ?

**Comment by uBlock-user** [comment] 2019-05-12 20:22
If you want to recreate that Firefox bug, then open My Filters in uBO and add `||ethgen.ch^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval'` and refresh the page, while keeping the rest of the rules of uMatrix above same and you will be able to reproduce that bug, which I can also do.

**Comment by gorhill** [comment] 2019-05-12 20:22
Did you enable font-blocking switch in uBO? This causes a CSP to be inserted.

Also, this will be a problem with filter lists, as there are many filters which purpose is to insert CSP on some sites.

Because of that Firefox issue, it is not recommended to use two extensions which injects CSPs.

**Comment by mowgli** [comment] 2019-05-12 20:31
Sure I use font filtering. That is one think why I want to have ublock.

So there is no way around?

**Comment by uBlock-user** [comment] 2019-05-12 20:33
> Sure I use font filtering

That's how you're triggering the Firefox bug. Use a static filter instead of that dynamic switch to block fonts.

**Comment by gorhill** [comment] 2019-05-12 20:35
No way around, it's a Firefox issue. You can vote for it to make the case if affects many ([under "Details"](https://bugzilla.mozilla.org/show_bug.cgi?id=1462989)).

**Comment by uBlock-user** [comment] 2019-05-12 20:38
There was first official issue about this uBO tracker -- https://github.com/uBlockOrigin/uBlock-issues/issues/502

**Comment by uBlock-user** [comment] 2020-04-16 07:26
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1462989#c90

**Closed by uBlock-user** 2020-04-16 07:26 UTC
Labels: Firefox, external
