### ISSUE TITLE
Enabling allow and deny rules to top-domain only

### ISSUE THREAD

**Issue by terapty** [uBlockOrigin/uMatrix-issues#282] opened 2020-08-05 00:31 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue

    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix extension is wholly disabled or not installed
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

I'd like to be able to apply a rule only to the top-domain (or a sub-domain excluding descendants). This is more of a feature request. I am aware that the issue I describe is documented as normal behavior (I think in the "popup panel" part) and I was wondering if there is any technical, ethical (or otherwise) reason to this behavior and if a change could be considered. There are many cases in which I would like to allow for example a script from the top-domain to run without allowing sub-domain scripts to run (and I can't think of any examples in which denying top-domain elements without denying sub-domain elements would be useful, but I'm sure there are), this would help in enforcing a true "block all/allow exceptionally" policy.

### A specific URL where the issue occurs

NA

### Steps to Reproduce

1. Allow/deny a top-domain element (script, xhr...)
2. All sub-domains' element get white/blacklisted

### Ruleset

NA

### Supporting evidence

NA

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Mozilla Firefox for Ubuntu canonical 79.0 (64-bit)
* Operating System and version: Ubuntu Linux 5.3.0-62-generic

**Comment by gorhill** [comment] 2020-08-07 17:08
Duplicate of <https://github.com/gorhill/uMatrix/issues/584>.

I refused such request in the past, this is the equivalent of asking me a grand rewrite uMatrix.

**Closed as completed by gorhill** 2020-08-07 17:08 UTC
Labels: declined
