### ISSUE TITLE
Block/allow keyboard shortcuts/hotkeys

### ISSUE THREAD

**Issue by WorldCodeCentral** [uBlockOrigin/uMatrix-issues#250] opened 2020-04-20 00:55 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

Feature request: Add block/allow keyboard shortcuts/hotkeys of the page the user is on. Or is it out of scope for uMatrix because it's not a resource that gets loaded?

### A specific URL where the issue occurs

Any page with keyboard shortcuts on it.

### Steps to Reproduce

1. Go to a page with keyboard shortcuts
2. Notice inconvenience or be surprised shortcuts won't work (as expected)

Thanks a lot for uMatrix and your contributions to software freedom!

**Comment by uBlock-user** [comment] 2020-04-20 07:45
Are you on Firefox ?

**Comment by gorhill** [comment] 2020-04-20 11:43
Duplicate of <https://github.com/gorhill/uMatrix/issues/678>.

**Closed by gorhill** 2020-04-20 11:43 UTC
Labels: enhancement

**Comment by WorldCodeCentral** [comment] 2020-04-20 13:49
Hello, yes I am on Firefox. I don't think it matters though, because my suggestion was **not** to add shortcuts to control uMatrix, but to **block or allow pages to overwrite browser shortcuts with their own custom ones.**

I hope I'm not being annoying by replying, but I'm pretty sure this is a misunderstanding, as the linked supposed duplicate  gorhill/uMatrix#678 is about shortcuts to control uMatrix.

**Comment by gorhill** [comment] 2020-04-20 13:54
> block or allow pages to overwrite browser shortcuts with their own custom ones.

I consider this out of scope for uMatrix. uMatrix can block JavaScript, which will prevent pages from setting up keyboard event, but blocking specific portion of JavaScript code is beyond uMatrix's scope.

**Comment by gwarser** [comment] 2020-04-20 13:59
@WorldCodeCentral right click on page -> View Page Info -> Permissions -> Override Keyboard Shortcuts -> Block.

**Comment by WorldCodeCentral** [comment] 2020-04-20 16:08
Thanks for your replies! Okay, so that's how keyboard shortcuts work.

Gwarser, thanks, I knew that one (and I think these permissions should have the same interface as cookies and camera, location, etc) but these block not only the page's but the extensions' shortcuts as well. Seems like the method to do that does not look for Javascript code but uses a switch for shortcut overwriting or something. I'm afraid it's not available for use in webextensions though. There's a ticket in bugzilla for that also.

Cheers!
