### ISSUE TITLE
Extension error: TypeError: cookies is undefined

### ISSUE THREAD

**Issue by puchu** [uBlockOrigin/uMatrix-issues#209] opened 2019-12-07 23:54 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [x] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description
After I upgraded to Firefox 71.0 i get the following error/exception when FF is started

> 
> JavaScript error: , line 0: uncaught exception: 2147746065
> Extension error: TypeError: cookies is undefined moz-extension://86ce0190-77cd-41d0-82da-41a241cb7361/js/cookies.js 103
> [[Exception stack
> addCookiesToDict@moz-extension://86ce0190-77cd-41d0-82da-41a241cb7361/js/cookies.js:103:13
> Current stack
> applySafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:601:13
> wrapPromise/</<@resource://gre/modules/ExtensionCommon.jsm:824:20
> withLastError@resource://gre/modules/ExtensionCommon.jsm:743:14
> wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:812:16
> ]]

### Your environment

* uMatrix version: 1.4.0
* Browser Name and version: Firefox 71.0
* Operating System and version: Linux 5.4.2

**Comment by gwarser** [comment] 2019-12-08 01:15
All green here: https://firefox-storage-test.glitch.me/ ?

**Comment by puchu** [comment] 2019-12-08 13:39
Although a created a new profile the error showed up again but it seems I did something wrong. I couldn't reproduve the error with a new profile and after some investigation i found out that 

privacy.firstparty.isolate - true

was the reason of the crash. Is there a way to use privacy.firstparty.isolate and still use uMatrix without a crash on startup, although the error is shown it seems that uMatrix works normal

**Comment by gwarser** [comment] 2019-12-08 13:58
https://github.com/gorhill/uMatrix/issues/878 ?

**Comment by gwarser** [comment] 2019-12-08 14:03
cookies is undefined cookies.js:103
	    addCookiesToDict moz-extension://37c2fedf-eb6b-47e9-b6b9-3442e36d36af/js/cookies.js:103
	    apply self-hosted:1868
	    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:595
	    wrapPromise resource://gre/modules/ExtensionCommon.jsm:824
	    withLastError resource://gre/modules/ExtensionCommon.jsm:743
	    wrapPromise resource://gre/modules/ExtensionCommon.jsm:812

	Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. vapi-background.js:594
	    getAll moz-extension://37c2fedf-eb6b-47e9-b6b9-3442e36d36af/js/vapi-background.js:594

**Comment by uBlock-user** [comment] 2019-12-08 14:40
> Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. vapi-background.js:594
    getAll moz-extension://37c2fedf-eb6b-47e9-b6b9-3442e36d36af/js/vapi-background.js:594

That's all I see on Nightly.

**Comment by gorhill** [comment] 2020-02-20 22:28
I un-checked _"using a new, unmodified browser profile"_ since user originally failed to disclosed he modified `privacy.firstparty.isolate`.

**Comment by opusforlife2** [comment] 2020-02-22 11:39
@gorhill So does this confirm that the bug I experienced is caused by uMatrix and not Snowflake?

**Comment by gorhill** [comment] 2020-02-22 15:17
The issue arises when using uMatrix with the setting `privacy.firstparty.isolate` set to `true`.

**Comment by uBlock-user** [comment] 2020-02-22 15:47
I have `privacy.firstparty.isolate toggle` to `true` on Nightly and this appears --

![Capture](https://user-images.githubusercontent.com/21290713/75095210-962b8780-55b8-11ea-8226-3205ed1320fe.PNG)

**Comment by gorhill** [comment] 2020-03-01 14:13
Duplicate of <https://github.com/gorhill/uMatrix/issues/878>.

**Closed** 2020-05-27 03:50 UTC
Labels: duplicate
