### ISSUE TITLE
request blocked but its URL doesn't show on uMatrix 

### ISSUE THREAD

**Issue by gqqnbig** [uBlockOrigin/uMatrix-issues#138] opened 2019-04-24 06:02 UTC
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [x] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [x] uMatrix is the only extension
    - [x] uMatrix with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uMatrix
- [ ] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [x] I used the logger to rule out that the issue is caused by my ruleset

### Description

See the following.

### A specific URL where the issue occurs

Image URL not appearing for
https://qunxing.huijiwiki.com/wiki/%E8%BF%9C%E5%8F%A4%E9%87%87%E7%9F%BF%E6%97%A0%E4%BA%BA%E6%9C%BA 

CSS URL not appearing for https://source.android.com/setup/build/building

### Steps to Reproduce

1.  
Open https://qunxing.huijiwiki.com/wiki/%E8%BF%9C%E5%8F%A4%E9%87%87%E7%9F%BF%E6%97%A0%E4%BA%BA%E6%9C%BA 
2. After the page is fully loaded, inspect an image on Chrome Developer tool, notice the image URL is https://huiji-public.huijistatic.com/qunxing/uploads/1/1f/Engineering_research.png.
![chrome_2019-04-23_22-47-42](https://user-images.githubusercontent.com/614159/56635321-09bbdb80-661a-11e9-9fcf-b7027e80ef6a.png)

3. click uMatrix icon and check the matrix table

Expected behavior:

huiji-public.huijistatic.com should appear on the matrix table.

Actual behavior:

huiji-public.huijistatic.com doesn't appear. See the screenshot.

![chrome_2019-04-23_22-50-24](https://user-images.githubusercontent.com/614159/56635401-4e477700-661a-11e9-881b-2832472e45b2.png)

### Ruleset

```
matrix-off: about-scheme true
matrix-off: behind-the-scene true
matrix-off: chrome-extension-scheme true
matrix-off: chrome-scheme true
matrix-off: opera-scheme true
noscript-spoof: * true
* * * block
* * css allow
* * frame block
* * image allow
* * script block
* 1st-party * allow
* 1st-party cookie block
* 1st-party frame allow
* 1st-party script allow
```

with No Hosts rules and ruleset recipes.

### Supporting evidence

No instance of huiji-public.huijistatic.com on uMatrix logger.

![捕获](https://user-images.githubusercontent.com/614159/56635672-ee6ec180-6655-11e9-81e7-1a14e7e56e95.JPG)

### Your environment

* uMatrix version: 1.3.16
* Browser Name and version: Chrome  73.0.3683.103
* Operating System and version: Windows 10 1803

**Comment by uBlock-user** [comment] 2019-04-24 06:34
Disable all other extensions and try again.

**Comment by gqqnbig** [comment] 2019-04-24 14:31
@uBlock-user Hi, recorded a gif showing how I reproduce it.

In the gif, I deleted Chrome's user data folder, so that Chrome starts as a brand new. Switch Chrome to English, so that other people can read the interface. Open https://qunxing.huijiwiki.com/wiki/%E8%BF%9C%E5%8F%A4%E9%87%87%E7%9F%BF%E6%97%A0%E4%BA%BA%E6%9C%BA, the icons on the page load correctly. Install uMatrix, and reload the page. The icons are broken. Remove uMatrix, the icons load again.

Please check. Thanks.
![reproduce](https://user-images.githubusercontent.com/614159/56667552-e79a7b80-6662-11e9-89e3-2b5caf552659.gif)

**Comment by gwarser** [comment] 2019-04-24 16:55
It's service worker issue. Solutions - hard reload or allow xhr or block service workers.

**Comment by uBlock-user** [comment] 2019-04-25 05:19
@gqqnbig That's not what I asked, and I still can't reproduce it. `huiji-public.huijistatic.com` always appears on my end.

**Comment by gqqnbig** [comment] 2019-04-25 05:50
@uBlock-user You asked "Disable all other extensions and try again." That is what I did. How can I improve my demenstration?

**Comment by uBlock-user** [comment] 2019-04-25 06:00
I meant just disable the extensions in chrome://extensions, not go around deleting the whole user data folder, that was excessive, but anyways, that's unrelated as to why it only happens to you.

**Comment by gorhill** [comment] 2019-04-25 10:32
Did you try to hard reload as pointed out by @gwarser?

**Comment by gqqnbig** [comment] 2019-04-30 00:11
Force refresh solves the problem.

**Comment by gorhill** [comment] 2019-05-04 16:13
Duplicate of <https://github.com/uBlockOrigin/uMatrix-issues/issues/92>.

**Closed by gorhill** 2019-05-04 16:13 UTC
Labels: duplicate
